import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
function p(t:string,s:string,d:'EASY'|'MEDIUM'|'HARD',o:number,story:string,pat:string,patEx:string,vs:any[],sols:any,cx:any,mem:string,quiz:any[],hints:string[],mistakes:string[]){return{title:t,slug:s,difficulty:d,order:o,story,visualSteps:JSON.stringify(vs),pattern:pat,patternExplanation:patEx,solutions:JSON.stringify(sols),complexity:JSON.stringify(cx),memoryTrick:mem,quiz:JSON.stringify(quiz),hints:JSON.stringify(hints),commonMistakes:JSON.stringify(mistakes)};}
function sol(py:string,j:string,c:string){return{python:{code:py,lineExplanations:py.split('\n').map(()=>'')},java:{code:j,lineExplanations:j.split('\n').map(()=>'')},cpp:{code:c,lineExplanations:c.split('\n').map(()=>'')}}}
function mcq(q:string,o:string[],c:number,e:string){return{type:'multiple_choice',question:q,options:o,correct:c,explanation:e}}
async function seed(slug:string,problems:any[]){const topic=await prisma.topic.findUnique({where:{slug}});if(!topic){console.log(`Topic ${slug} not found`);return;}for(const prob of problems){const e=await prisma.problem.findUnique({where:{slug:prob.slug}});if(e){continue;}await prisma.problem.create({data:{...prob,topicId:topic.id}});console.log(`  ✅ ${prob.slug}`);}}

async function main(){
console.log('🚀 Batch 5: Adv Graphs, 1D DP, 2D DP, Greedy, Intervals, Math, Bits\n');

// ==================== ADVANCED GRAPHS (6) ====================
console.log('🗺️ Advanced Graphs');
await seed('advanced-graphs',[
p('Reconstruct Itinerary','reconstruct-itinerary','HARD',1,"Given airline tickets, find the route that uses all tickets starting from JFK. Use Hierholzer's algorithm (Eulerian path): DFS through edges, add to result in post-order.",'Hierholzer Eulerian Path','Build adjacency list sorted in reverse. DFS greedily. Add to result after all edges used from a node. Reverse result.',[{step:1,description:"tickets=[[JFK,SFO],[JFK,ATL],[SFO,ATL],[ATL,JFK],[ATL,SFO]]",diagram:"JFK→ATL→JFK→SFO→ATL→SFO"}],
sol("def findItinerary(tickets):\n    from collections import defaultdict\n    graph = defaultdict(list)\n    for a, b in sorted(tickets, reverse=True):\n        graph[a].append(b)\n    route = []\n    def dfs(airport):\n        while graph[airport]:\n            dfs(graph[airport].pop())\n        route.append(airport)\n    dfs('JFK')\n    return route[::-1]","public List<String> findItinerary(List<List<String>> tickets) {\n    Map<String,PriorityQueue<String>> g=new HashMap<>();\n    for(var t:tickets)g.computeIfAbsent(t.get(0),k->new PriorityQueue<>()).add(t.get(1));\n    List<String> route=new ArrayList<>();\n    void dfs(String a){var q=g.get(a);while(q!=null&&!q.isEmpty())dfs(q.poll());route.add(0,a);}\n    dfs(\"JFK\");return route;\n}","// C++ with map<string,multiset<string>>"),
{time:'O(E log E)',space:'O(E)',simpleExplanation:"Sort edges + DFS through all = O(E log E)."},"EULERIAN PATH = DFS post-order. Visit all edges. Reverse = valid path.",
[mcq("Why add to result in post-order?",["Post-order ensures we use ALL edges before recording the node","Pre-order is wrong","It's alphabetical","No reason"],0,"Adding after all edges from a node are used ensures no dead-ends. Reverse gives the correct order.")],
["Build sorted adjacency list. DFS from JFK.","Pop edges as you use them.","Add to result after all edges exhausted. Reverse."],
["Not sorting destinations lexicographically","Pre-order traversal (misses edge cases)"]
),
p('Min Cost to Connect All Points','min-cost-to-connect-all-points','MEDIUM',2,"Connect all points with minimum total Manhattan distance. This is Minimum Spanning Tree! Use Prim's or Kruskal's algorithm.",'Prim\'s MST','Start from any point. Greedily add the cheapest edge connecting a new point. Use a min-heap.',[{step:1,description:"points=[[0,0],[2,2],[3,10],[5,2],[7,0]]",diagram:"MST connects all with minimum total distance = 20"}],
sol("import heapq\ndef minCostConnectPoints(points):\n    n=len(points)\n    visited=set()\n    heap=[(0,0)]  # (cost, point_index)\n    total=0\n    while len(visited)<n:\n        cost,i=heapq.heappop(heap)\n        if i in visited: continue\n        visited.add(i)\n        total+=cost\n        for j in range(n):\n            if j not in visited:\n                dist=abs(points[i][0]-points[j][0])+abs(points[i][1]-points[j][1])\n                heapq.heappush(heap,(dist,j))\n    return total","public int minCostConnectPoints(int[][] p) {\n    int n=p.length; boolean[] vis=new boolean[n];\n    PriorityQueue<int[]> pq=new PriorityQueue<>((a,b)->a[0]-b[0]);\n    pq.add(new int[]{0,0}); int total=0,cnt=0;\n    while(cnt<n){int[] top=pq.poll();if(vis[top[1]])continue;vis[top[1]]=true;total+=top[0];cnt++;\n    for(int j=0;j<n;j++)if(!vis[j])pq.add(new int[]{Math.abs(p[top[1]][0]-p[j][0])+Math.abs(p[top[1]][1]-p[j][1]),j});\n    }return total;\n}","int minCostConnectPoints(vector<vector<int>>& p) {\n    int n=p.size(); vector<bool> vis(n);\n    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> pq;\n    pq.push({0,0}); int total=0,cnt=0;\n    while(cnt<n){auto[cost,i]=pq.top();pq.pop();if(vis[i])continue;vis[i]=true;total+=cost;cnt++;\n    for(int j=0;j<n;j++)if(!vis[j])pq.push({abs(p[i][0]-p[j][0])+abs(p[i][1]-p[j][1]),j});\n    }return total;\n}"),
{time:'O(n² log n)',space:'O(n²)',simpleExplanation:"Complete graph with n² edges. Heap operations."},"MIN COST CONNECT = Prim's MST. Greedily add cheapest edge to unvisited point.",
[mcq("What algorithm finds MST?",["Binary Search","Prim's or Kruskal's","DFS","Topological Sort"],1,"Minimum Spanning Tree algorithms: Prim's (grow from a vertex) or Kruskal's (sort all edges, union-find).")],
["This is a Minimum Spanning Tree problem.","Prim's: start from any point, greedily add cheapest edge to new point.","Use min-heap for efficient selection."],
["Using DFS/BFS (finds connectivity, not MST)","Not using Manhattan distance"]
),
p('Network Delay Time','network-delay-time','MEDIUM',3,"Send a signal from node k. How long until all nodes receive it? Shortest paths from k to all nodes = Dijkstra's algorithm! The answer is the maximum shortest path.",'Dijkstra\'s Shortest Path','Dijkstra from source k. Track min time to each node. Answer = max of all min times. If any unreachable → -1.',[{step:1,description:"times=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2",diagram:"From 2: to 1=1, to 3=1, to 4=2. Max=2 ✅"}],
sol("import heapq\ndef networkDelayTime(times, n, k):\n    graph = [[] for _ in range(n+1)]\n    for u,v,w in times: graph[u].append((v,w))\n    dist = [float('inf')]*(n+1)\n    dist[k] = 0\n    heap = [(0, k)]\n    while heap:\n        d, u = heapq.heappop(heap)\n        if d > dist[u]: continue\n        for v, w in graph[u]:\n            if dist[u] + w < dist[v]:\n                dist[v] = dist[u] + w\n                heapq.heappush(heap, (dist[v], v))\n    mx = max(dist[1:])\n    return mx if mx < float('inf') else -1","public int networkDelayTime(int[][] times, int n, int k) {\n    List<int[]>[] g=new List[n+1];\n    for(int i=0;i<=n;i++)g[i]=new ArrayList<>();\n    for(int[] t:times)g[t[0]].add(new int[]{t[1],t[2]});\n    int[] dist=new int[n+1];Arrays.fill(dist,Integer.MAX_VALUE);dist[k]=0;\n    PriorityQueue<int[]> pq=new PriorityQueue<>((a,b)->a[0]-b[0]);\n    pq.add(new int[]{0,k});\n    while(!pq.isEmpty()){int[] top=pq.poll();if(top[0]>dist[top[1]])continue;for(int[] e:g[top[1]])if(dist[top[1]]+e[1]<dist[e[0]]){dist[e[0]]=dist[top[1]]+e[1];pq.add(new int[]{dist[e[0]],e[0]});}}\n    int mx=0;for(int i=1;i<=n;i++){if(dist[i]==Integer.MAX_VALUE)return -1;mx=Math.max(mx,dist[i]);}\n    return mx;\n}","int networkDelayTime(vector<vector<int>>& times, int n, int k) {\n    vector<vector<pair<int,int>>> g(n+1);\n    for(auto& t:times)g[t[0]].push_back({t[1],t[2]});\n    vector<int> dist(n+1,INT_MAX);dist[k]=0;\n    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> pq;\n    pq.push({0,k});\n    while(!pq.empty()){auto[d,u]=pq.top();pq.pop();if(d>dist[u])continue;for(auto[v,w]:g[u])if(dist[u]+w<dist[v]){dist[v]=dist[u]+w;pq.push({dist[v],v});}}\n    int mx=0;for(int i=1;i<=n;i++){if(dist[i]==INT_MAX)return -1;mx=max(mx,dist[i]);}\n    return mx;\n}"),
{time:'O(E log V)',space:'O(V+E)',simpleExplanation:"Dijkstra with min-heap = O(E log V)."},"NETWORK DELAY = Dijkstra from source. Answer = MAX of all shortest paths.",
[mcq("Why Dijkstra and not BFS?",["Edges have different weights","BFS only works for unweighted graphs (or equal weights)","Dijkstra is always better","BFS can't handle graphs"],1,"BFS assumes all edges cost 1. Dijkstra handles weighted edges by always processing the closest unvisited node.")],
["Build weighted adjacency list. Dijkstra from k.","Track min distance to each node.","Answer = max of all distances. Any unreachable → -1."],
["Using BFS on weighted graph","Not handling unreachable nodes"]
),
p('Swim in Rising Water','swim-in-rising-water','HARD',4,"Grid of elevations. Swim from (0,0) to (n-1,n-1). At time t, you can swim to cells with elevation ≤ t. Find minimum t. Binary search on t + BFS, or use Dijkstra/Prim treating max elevation as cost.",'Modified Dijkstra / Binary Search + BFS','Use min-heap Dijkstra where cost = max elevation on path. Or binary search on time t, BFS to check if path exists.',[{step:1,description:"grid=[[0,2],[1,3]]",diagram:"Path 0→2→3: max=3. Path 0→1→3: max=3. Answer: 3"}],
sol("import heapq\ndef swimInWater(grid):\n    n=len(grid)\n    heap=[(grid[0][0],0,0)]\n    visited=set()\n    while heap:\n        t,r,c=heapq.heappop(heap)\n        if (r,c) in visited: continue\n        visited.add((r,c))\n        if r==n-1 and c==n-1: return t\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            nr,nc=r+dr,c+dc\n            if 0<=nr<n and 0<=nc<n and (nr,nc) not in visited:\n                heapq.heappush(heap,(max(t,grid[nr][nc]),nr,nc))\n    return -1","public int swimInWater(int[][] grid) {\n    int n=grid.length;\n    PriorityQueue<int[]> pq=new PriorityQueue<>((a,b)->a[0]-b[0]);\n    pq.add(new int[]{grid[0][0],0,0});\n    boolean[][] vis=new boolean[n][n];\n    int[][] dirs={{0,1},{0,-1},{1,0},{-1,0}};\n    while(!pq.isEmpty()){\n        int[] top=pq.poll();\n        int t=top[0],r=top[1],c=top[2];\n        if(vis[r][c])continue;vis[r][c]=true;\n        if(r==n-1&&c==n-1)return t;\n        for(int[] d:dirs){int nr=r+d[0],nc=c+d[1];\n        if(nr>=0&&nr<n&&nc>=0&&nc<n&&!vis[nr][nc])pq.add(new int[]{Math.max(t,grid[nr][nc]),nr,nc});}\n    }return -1;\n}","int swimInWater(vector<vector<int>>& grid) {\n    int n=grid.size();\n    priority_queue<tuple<int,int,int>,vector<tuple<int,int,int>>,greater<>> pq;\n    pq.push({grid[0][0],0,0});\n    vector<vector<bool>> vis(n,vector<bool>(n));\n    int dirs[]={0,1,0,-1,0};\n    while(!pq.empty()){\n        auto[t,r,c]=pq.top();pq.pop();\n        if(vis[r][c])continue;vis[r][c]=true;\n        if(r==n-1&&c==n-1)return t;\n        for(int d=0;d<4;d++){int nr=r+dirs[d],nc=c+dirs[d+1];\n        if(nr>=0&&nr<n&&nc>=0&&nc<n&&!vis[nr][nc])pq.push({max(t,grid[nr][nc]),nr,nc});}\n    }return -1;\n}"),
{time:'O(n² log n)',space:'O(n²)',simpleExplanation:"Dijkstra on n² cells with heap = O(n² log n)."},"SWIM = Dijkstra where cost = MAX elevation on path. Min-heap gives optimal path.",
[mcq("What's the 'cost' of a path?",["Sum of elevations","Maximum elevation along the path","Number of steps","Minimum elevation"],1,"We need the minimum time t where we can reach all cells on the path. t = max elevation encountered.")],
["Model as graph. Edge cost = max(current time, neighbor elevation).","Dijkstra finds the path minimizing the maximum elevation.","Min-heap processes lowest-cost paths first."],
["Using sum instead of max for path cost","Regular BFS doesn't account for elevation weights"]
),
p('Cheapest Flights Within K Stops','cheapest-flights-within-k-stops','MEDIUM',5,"Find cheapest flight from src to dst with at most k stops. Modified Dijkstra or BFS level-by-level (k+1 levels). Or Bellman-Ford with k+1 iterations.",'Modified BFS / Bellman-Ford','BFS level by level (each level = one flight). Track min cost to each node. Stop after k+1 levels.',[{step:1,description:"n=4, flights=[[0,1,100],[1,2,100],[2,0,100],[1,3,600],[2,3,200]], src=0,dst=3,k=1",diagram:"0→1→3=700 (1 stop). 0→1→2→3=400 but 2 stops>k. Answer: 700"}],
sol("def findCheapestPrice(n, flights, src, dst, k):\n    prices = [float('inf')] * n\n    prices[src] = 0\n    for _ in range(k + 1):\n        temp = prices[:]\n        for u, v, w in flights:\n            if prices[u] != float('inf'):\n                temp[v] = min(temp[v], prices[u] + w)\n        prices = temp\n    return prices[dst] if prices[dst] != float('inf') else -1","public int findCheapestPrice(int n, int[][] flights, int src, int dst, int k) {\n    int[] prices=new int[n];Arrays.fill(prices,Integer.MAX_VALUE);prices[src]=0;\n    for(int i=0;i<=k;i++){\n        int[] temp=prices.clone();\n        for(int[] f:flights)if(prices[f[0]]!=Integer.MAX_VALUE)temp[f[1]]=Math.min(temp[f[1]],prices[f[0]]+f[2]);\n        prices=temp;\n    }\n    return prices[dst]==Integer.MAX_VALUE?-1:prices[dst];\n}","int findCheapestPrice(int n, vector<vector<int>>& flights, int src, int dst, int k) {\n    vector<int> prices(n,INT_MAX);prices[src]=0;\n    for(int i=0;i<=k;i++){\n        auto temp=prices;\n        for(auto& f:flights)if(prices[f[0]]!=INT_MAX)temp[f[1]]=min(temp[f[1]],prices[f[0]]+f[2]);\n        prices=temp;\n    }\n    return prices[dst]==INT_MAX?-1:prices[dst];\n}"),
{time:'O(k*E)',space:'O(V)',simpleExplanation:"k+1 iterations over all edges = O(k*E)."},"K STOPS = Bellman-Ford with k+1 iterations. Copy prices array each iteration to limit stops!",
[mcq("Why copy the prices array each iteration?",["To save memory","To prevent using more than one edge per iteration (limits stops)","Copying is faster","It's not necessary"],1,"Without copying, a chain of updates in one iteration could use multiple stops. Copying ensures each iteration adds at most one stop.")],
["Bellman-Ford relaxes all edges k+1 times (k stops = k+1 flights).","Copy prices before each iteration to limit hop count.","After k+1 iterations, prices[dst] = cheapest with ≤k stops."],
["Not copying prices (allows unlimited stops in one iteration)","Using standard Dijkstra (doesn't limit stops)"]
),
p('Alien Dictionary','alien-dictionary','HARD',6,"Given sorted alien words, determine the letter ordering. Compare adjacent words to find edge relationships (which letter comes before which). Then topological sort!",'Topological Sort from Comparisons','Compare adjacent words to find ordering constraints. Build directed graph. Topological sort = alien alphabet order.',[{step:1,description:"words=['wrt','wrf','er','ett','rftt']",diagram:"w→e, r→t, t→f, e→r → order: wertf"}],
sol("def alienOrder(words):\n    from collections import defaultdict, deque\n    graph = defaultdict(set)\n    indegree = {c: 0 for w in words for c in w}\n    for i in range(len(words)-1):\n        w1, w2 = words[i], words[i+1]\n        minLen = min(len(w1), len(w2))\n        if len(w1) > len(w2) and w1[:minLen] == w2[:minLen]: return ''\n        for j in range(minLen):\n            if w1[j] != w2[j]:\n                if w2[j] not in graph[w1[j]]:\n                    graph[w1[j]].add(w2[j])\n                    indegree[w2[j]] += 1\n                break\n    queue = deque([c for c in indegree if indegree[c] == 0])\n    result = []\n    while queue:\n        c = queue.popleft()\n        result.append(c)\n        for nei in graph[c]:\n            indegree[nei] -= 1\n            if indegree[nei] == 0: queue.append(nei)\n    return ''.join(result) if len(result) == len(indegree) else ''","// Java: similar approach with HashMap + BFS topo sort","// C++: similar with unordered_map + queue topo sort"),
{time:'O(C)',space:'O(V+E)',simpleExplanation:"C = total characters across all words. V = unique letters."},"ALIEN DICT = compare adjacent words for ordering constraints → topological sort!",
[mcq("How do we find ordering constraints?",["Sort all letters","Compare adjacent words character by character until they differ","Check letter frequencies","Use a hash map"],1,"First differing character between adjacent words tells us: char_from_word1 comes BEFORE char_from_word2.")],
["Compare consecutive words to find ordering edges.","Build directed graph of letter orderings.","Topological sort = alien alphabet. Cycle = invalid."],
["Not handling prefix case (abc before ab = invalid)","Only comparing first and last words"]
),
]);

// ==================== 1D DYNAMIC PROGRAMMING (12) ====================
console.log('\n📝 1D Dynamic Programming');
await seed('1d-dynamic-programming',[
p('Climbing Stairs','climbing-stairs','EASY',1,"You can climb 1 or 2 stairs at a time. How many ways to reach step n? It's Fibonacci! ways(n) = ways(n-1) + ways(n-2). From step n-1 take 1 step, from n-2 take 2 steps.",'Bottom-Up DP (Fibonacci)','dp[i] = dp[i-1] + dp[i-2]. Same as Fibonacci! Base: dp[1]=1, dp[2]=2.',[{step:1,description:"n=5",diagram:"dp: 1,2,3,5,8. Answer: 8 ways"}],
sol("def climbStairs(n):\n    a, b = 1, 1\n    for _ in range(n - 1):\n        a, b = b, a + b\n    return b","public int climbStairs(int n) {\n    int a=1,b=1;\n    for(int i=1;i<n;i++){int t=b;b=a+b;a=t;}\n    return b;\n}","int climbStairs(int n) {\n    int a=1,b=1;\n    for(int i=1;i<n;i++){int t=b;b=a+b;a=t;}\n    return b;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One loop, two variables."},"CLIMBING STAIRS = Fibonacci. ways(n) = ways(n-1) + ways(n-2).",
[mcq("Why is this related to Fibonacci?",["Each step has 2 choices: from n-1 (1 step) or n-2 (2 steps) = same recurrence","Stairs look like spirals","It's a coincidence","Fibonacci is about rabbits, not stairs"],0,"ways(n) = ways(n-1) + ways(n-2) is exactly the Fibonacci recurrence!")],
["From step n, you came from n-1 or n-2.","So ways(n) = ways(n-1) + ways(n-2).","Optimize space: only need last two values."],
["Using recursion without memoization (O(2ⁿ))","Off-by-one in base cases"]
),
p('Min Cost Climbing Stairs','min-cost-climbing-stairs','EASY',2,"Each stair has a cost. You can start from step 0 or 1, climb 1 or 2 at a time. dp[i] = cost[i] + min(dp[i-1], dp[i-2]). Answer = min(dp[n-1], dp[n-2]).",'Bottom-Up DP','dp[i] = cost to reach step i = cost[i] + min(dp[i-1], dp[i-2]).',[{step:1,description:"cost=[10,15,20]",diagram:"dp[0]=10, dp[1]=15, dp[2]=10+20=30. Answer=min(15,30)=15"}],
sol("def minCostClimbingStairs(cost):\n    for i in range(2, len(cost)):\n        cost[i] += min(cost[i-1], cost[i-2])\n    return min(cost[-1], cost[-2])","public int minCostClimbingStairs(int[] cost) {\n    for(int i=2;i<cost.length;i++)cost[i]+=Math.min(cost[i-1],cost[i-2]);\n    return Math.min(cost[cost.length-1],cost[cost.length-2]);\n}","int minCostClimbingStairs(vector<int>& cost) {\n    for(int i=2;i<cost.size();i++)cost[i]+=min(cost[i-1],cost[i-2]);\n    return min(cost.back(),cost[cost.size()-2]);\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass modifying in-place."},"MIN COST STAIRS = dp[i] = cost[i] + min(dp[i-1], dp[i-2]). Answer = min of last two.",
[mcq("Why is the answer min(dp[n-1], dp[n-2])?",["We can reach the top from either of the last two steps","The top step is always cheaper","We must end at the last step","The minimum is always at n-2"],0,"We can step OVER the last step (from n-2, take 2 steps) or land on it (from n-1, take 1 step).")],
["From each step, cost = your cost + min of two previous.","Build bottom-up from step 2.","Answer = min of reaching last or second-to-last step."],
["Only considering dp[n-1] as the answer","Not modifying in-place (works but uses extra space)"]
),
p('House Robber','house-robber','MEDIUM',3,"Rob houses but never two adjacent. dp[i] = max(rob this house + dp[i-2], skip this house + dp[i-1]). Classic include/exclude DP!",'DP Include/Exclude','dp[i] = max(nums[i] + dp[i-2], dp[i-1]). Include current + best without adjacent, or skip current.',[{step:1,description:"nums=[1,2,3,1]",diagram:"dp: 1,2,4,4. Rob houses 0,2 → 1+3=4 ✅"}],
sol("def rob(nums):\n    a, b = 0, 0\n    for num in nums:\n        a, b = b, max(b, a + num)\n    return b","public int rob(int[] nums) {\n    int a=0,b=0;\n    for(int n:nums){int t=b;b=Math.max(b,a+n);a=t;}\n    return b;\n}","int rob(vector<int>& nums) {\n    int a=0,b=0;\n    for(int n:nums){int t=b;b=max(b,a+n);a=t;}\n    return b;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass, two variables."},"HOUSE ROBBER = max(rob_this + dp[i-2], skip + dp[i-1]). Include/exclude pattern!",
[mcq("Why can't we just rob all even-indexed or all odd-indexed houses?",["Sometimes the optimal skips multiple in a row","The pattern isn't always alternating","Greedy doesn't work here","It depends on n"],0,"[2,1,1,2]: robbing 0,3 gives 4. Alternating (0,2)=3 or (1,3)=3. DP finds the optimal mix.")],
["At each house: rob it (+ dp[i-2]) or skip it (dp[i-1]).","Take the max.","Optimize: only need last two values."],
["Always alternating (greedy doesn't work)","Not considering the skip option"]
),
p('House Robber II','house-robber-ii','MEDIUM',4,"Same as House Robber but houses are in a circle (first and last are adjacent). Solution: run House Robber twice — once excluding the first house, once excluding the last. Take max!",'Circular DP = Two Linear DPs','Circle means house 0 and n-1 are adjacent. Solve twice: nums[1..n-1] and nums[0..n-2]. Take max.',[{step:1,description:"nums=[2,3,2]",diagram:"Can't rob both 2s. Rob [3]=3 or [2,2] can't both. Answer: 3"}],
sol("def rob(nums):\n    if len(nums)==1: return nums[0]\n    def helper(arr):\n        a,b=0,0\n        for n in arr: a,b=b,max(b,a+n)\n        return b\n    return max(helper(nums[1:]), helper(nums[:-1]))","public int rob(int[] nums) {\n    if(nums.length==1)return nums[0];\n    return Math.max(helper(nums,0,nums.length-2),helper(nums,1,nums.length-1));\n}\nint helper(int[] nums,int lo,int hi){\n    int a=0,b=0;\n    for(int i=lo;i<=hi;i++){int t=b;b=Math.max(b,a+nums[i]);a=t;}\n    return b;\n}","int rob(vector<int>& nums) {\n    if(nums.size()==1)return nums[0];\n    auto h=[&](int lo,int hi){int a=0,b=0;for(int i=lo;i<=hi;i++){int t=b;b=max(b,a+nums[i]);a=t;}return b;};\n    return max(h(0,nums.size()-2),h(1,nums.size()-1));\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"Two passes of O(n) = O(n)."},"CIRCULAR ROBBER = solve TWICE: skip first house OR skip last house. Take max!",
[mcq("Why solve twice?",["If we rob house 0, we can't rob house n-1 (adjacent in circle). Two separate runs cover both cases.","It's more accurate","Once isn't enough","To handle odd/even separately"],0,"Circular adjacency means 0 and n-1 can't both be robbed. Running without 0 and without n-1 covers all valid combinations.")],
["Circle = first and last are adjacent.","Run House Robber on [1..n-1] and [0..n-2].","Take the maximum of both."],
["Not handling the circular constraint","Running House Robber once on the full array"]
),
p('Longest Palindromic Substring','longest-palindromic-substring','MEDIUM',5,"Find the longest palindrome in a string. Expand around each center! Try every character as center (odd length) and every pair as center (even length). Expand outward while matching.",'Expand Around Center','For each index, expand outward while chars match. Try both odd (single center) and even (double center) palindromes.',[{step:1,description:"s='babad'",diagram:"Center 'a'(idx 1): expand → 'bab' (length 3). Center 'b'(idx 2): 'aba'. Answer: 'bab' or 'aba'"}],
sol("def longestPalindrome(s):\n    res = ''\n    for i in range(len(s)):\n        for l, r in [(i,i), (i,i+1)]:\n            while l>=0 and r<len(s) and s[l]==s[r]:\n                if r-l+1 > len(res): res = s[l:r+1]\n                l -= 1; r += 1\n    return res","public String longestPalindrome(String s) {\n    int start=0,maxLen=0;\n    for(int i=0;i<s.length();i++)for(int j:{0,1}){\n        int l=i,r=i+j;\n        while(l>=0&&r<s.length()&&s.charAt(l)==s.charAt(r)){if(r-l+1>maxLen){start=l;maxLen=r-l+1;}l--;r++;}\n    }\n    return s.substring(start,start+maxLen);\n}","string longestPalindrome(string s) {\n    int start=0,maxLen=0;\n    for(int i=0;i<s.size();i++)for(int j:{0,1}){\n        int l=i,r=i+j;\n        while(l>=0&&r<(int)s.size()&&s[l]==s[r]){if(r-l+1>maxLen){start=l;maxLen=r-l+1;}l--;r++;}\n    }\n    return s.substr(start,maxLen);\n}"),
{time:'O(n²)',space:'O(1)',simpleExplanation:"n centers, each expand up to n = O(n²). No extra space!"},"LONGEST PALINDROME = expand from each center. Try odd AND even lengths!",
[mcq("Why try both odd and even centers?",["'aba' has center at 'b' (odd), 'abba' has center between b's (even)","Even palindromes don't exist","Odd is always longer","To double-check"],0,"Odd palindromes have a single center character. Even palindromes have the center between two characters.")],
["Try each index as center of odd palindrome.","Try each adjacent pair as center of even palindrome.","Expand outward while characters match. Track longest."],
["Only checking odd-length palindromes","Using DP O(n²) space when expand-around-center uses O(1)"]
),
p('Palindromic Substrings','palindromic-substrings','MEDIUM',6,"Count ALL palindromic substrings. Same expand-around-center approach but COUNT instead of finding the longest.",'Expand Around Center + Count','Same as longest palindrome but increment count for each valid expansion.',[{step:1,description:"s='aaa'",diagram:"Palindromes: a,a,a,aa,aa,aaa = 6"}],
sol("def countSubstrings(s):\n    count = 0\n    for i in range(len(s)):\n        for l, r in [(i,i), (i,i+1)]:\n            while l>=0 and r<len(s) and s[l]==s[r]:\n                count += 1\n                l -= 1; r += 1\n    return count","public int countSubstrings(String s) {\n    int count=0;\n    for(int i=0;i<s.length();i++)for(int j:{0,1}){\n        int l=i,r=i+j;\n        while(l>=0&&r<s.length()&&s.charAt(l)==s.charAt(r)){count++;l--;r++;}\n    }\n    return count;\n}","int countSubstrings(string s) {\n    int count=0;\n    for(int i=0;i<s.size();i++)for(int j:{0,1}){\n        int l=i,r=i+j;\n        while(l>=0&&r<(int)s.size()&&s[l]==s[r]){count++;l--;r++;}\n    }\n    return count;\n}"),
{time:'O(n²)',space:'O(1)',simpleExplanation:"n centers, each expand up to n = O(n²)."},"COUNT PALINDROMES = expand from each center (odd+even). Each expansion = one more palindrome!",
[mcq("Every single character is a palindrome, right?",["Yes — 'a' reads the same forwards and backwards","No, only vowels","Only if it's repeated","Depends on context"],0,"Any single character is trivially a palindrome. So a string of length n has at least n palindromic substrings.")],
["Same technique as longest palindromic substring.","But instead of tracking the longest, increment a counter for each valid expansion.","Each expansion step finds one new palindrome."],
["Forgetting to count single characters","Not trying even-length palindromes"]
),
p('Decode Ways','decode-ways','MEDIUM',7,"Map 1→A, 2→B, ..., 26→Z. Count ways to decode a digit string. DP: each digit can be decoded alone (1-9) or as part of a two-digit number (10-26).",'DP with 1-digit and 2-digit choices','dp[i] = ways to decode s[0..i]. If s[i] valid (1-9): dp[i] += dp[i-1]. If s[i-1..i] valid (10-26): dp[i] += dp[i-2].',[{step:1,description:"s='226'",diagram:"2|2|6, 22|6, 2|26 → 3 ways"}],
sol("def numDecodings(s):\n    if s[0] == '0': return 0\n    a, b = 1, 1\n    for i in range(1, len(s)):\n        temp = 0\n        if s[i] != '0': temp = b\n        if 10 <= int(s[i-1:i+1]) <= 26: temp += a\n        a, b = b, temp\n    return b","public int numDecodings(String s) {\n    if(s.charAt(0)=='0')return 0;\n    int a=1,b=1;\n    for(int i=1;i<s.length();i++){\n        int temp=0;\n        if(s.charAt(i)!='0')temp=b;\n        int two=Integer.parseInt(s.substring(i-1,i+1));\n        if(two>=10&&two<=26)temp+=a;\n        a=b;b=temp;\n    }\n    return b;\n}","int numDecodings(string s) {\n    if(s[0]=='0')return 0;\n    int a=1,b=1;\n    for(int i=1;i<s.size();i++){\n        int temp=0;\n        if(s[i]!='0')temp=b;\n        int two=(s[i-1]-'0')*10+(s[i]-'0');\n        if(two>=10&&two<=26)temp+=a;\n        a=b;b=temp;\n    }\n    return b;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass, two variables."},"DECODE WAYS = dp[i] = (single digit valid? dp[i-1]) + (two digits valid? dp[i-2]).",
[mcq("What makes a single digit valid for decoding?",["Any digit 0-9","Digits 1-9 (0 can't be decoded alone)","Only digits 1-2","All digits are valid"],1,"'0' alone doesn't map to any letter. Only 1-9 are valid single digits. 0 must be part of 10 or 20.")],
["Single digit (1-9): add dp[i-1]. Two digits (10-26): add dp[i-2].","'0' can't be decoded alone — only as part of 10 or 20.","Watch for edge cases with leading zeros."],
["Not handling '0' correctly","Allowing '06' as a valid two-digit code (must be 10-26)"]
),
p('Coin Change','coin-change','MEDIUM',8,"Find minimum coins to make amount. dp[i] = min coins for amount i. For each coin, dp[i] = min(dp[i], dp[i-coin] + 1). Classic unbounded knapsack!",'Bottom-Up DP','dp[i] = min coins to make amount i. For each amount, try each coin. dp[i] = min(dp[i], dp[i-coin]+1).',[{step:1,description:"coins=[1,5,11], amount=15",diagram:"dp[15]=3 (5+5+5). Greedy (11+1+1+1+1)=5 coins → DP is better!"}],
sol("def coinChange(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for coin in coins:\n            if coin <= i:\n                dp[i] = min(dp[i], dp[i - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1","public int coinChange(int[] coins, int amount) {\n    int[] dp=new int[amount+1];\n    Arrays.fill(dp,amount+1);\n    dp[0]=0;\n    for(int i=1;i<=amount;i++)for(int c:coins)if(c<=i)dp[i]=Math.min(dp[i],dp[i-c]+1);\n    return dp[amount]>amount?-1:dp[amount];\n}","int coinChange(vector<int>& coins, int amount) {\n    vector<int> dp(amount+1,amount+1);\n    dp[0]=0;\n    for(int i=1;i<=amount;i++)for(int c:coins)if(c<=i)dp[i]=min(dp[i],dp[i-c]+1);\n    return dp[amount]>amount?-1:dp[amount];\n}"),
{time:'O(amount * coins)',space:'O(amount)',simpleExplanation:"For each amount (up to target), try each coin = O(amount * coins)."},"COIN CHANGE = dp[i] = min(dp[i-coin] + 1) for each coin. Classic DP!",
[mcq("Why doesn't greedy work for coin change?",["It always works","Greedy picks largest coin first but might miss the optimal solution (e.g., coins [1,5,11], amount 15)","Greedy is too slow","Greedy only works with sorted coins"],1,"Greedy gives 11+1+1+1+1=5 coins for 15. Optimal is 5+5+5=3 coins. DP explores all possibilities.")],
["dp[0]=0. For each amount 1..target, try each coin.","dp[i] = min(dp[i], dp[i-coin]+1).","Return dp[amount] or -1 if impossible."],
["Using greedy (doesn't guarantee minimum)","Not initializing dp with infinity","Off-by-one in loop bounds"]
),
p('Maximum Product Subarray','maximum-product-subarray','MEDIUM',9,"Find subarray with maximum product. Tricky because negatives can become positive when multiplied! Track both MAX and MIN at each position. A negative × min_so_far might become the new max!",'DP Track Max AND Min','Track curMax and curMin. At each element: new candidates are num, curMax*num, curMin*num. Update both.',[{step:1,description:"nums=[2,3,-2,4]",diagram:"2*3=6, but -2 flips sign. 4 alone=4. Max=6"}],
sol("def maxProduct(nums):\n    result = nums[0]\n    curMax = curMin = 1\n    for n in nums:\n        vals = (n, curMax * n, curMin * n)\n        curMax, curMin = max(vals), min(vals)\n        result = max(result, curMax)\n    return result","public int maxProduct(int[] nums) {\n    int res=nums[0],curMax=1,curMin=1;\n    for(int n:nums){\n        int a=curMax*n,b=curMin*n;\n        curMax=Math.max(n,Math.max(a,b));\n        curMin=Math.min(n,Math.min(a,b));\n        res=Math.max(res,curMax);\n    }\n    return res;\n}","int maxProduct(vector<int>& nums) {\n    int res=nums[0],curMax=1,curMin=1;\n    for(int n:nums){\n        int a=curMax*n,b=curMin*n;\n        curMax=max({n,a,b});\n        curMin=min({n,a,b});\n        res=max(res,curMax);\n    }\n    return res;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass tracking max and min."},"MAX PRODUCT = track BOTH max AND min (negatives flip!). Three candidates: num, max*num, min*num.",
[mcq("Why track both max AND min?",["A negative number × negative min = positive max!","Min is needed for debugging","Convention","Only max matters"],0,"[-2,3,-4]: min at -4 is -24. Next multiply by -4: -24*-4=96! Huge positive from tracking the min.")],
["Negative × negative = positive. So min matters!","Three candidates each step: num alone, max*num, min*num.","Update both max and min, track global result."],
["Only tracking max (misses negative × negative = positive)","Not considering starting a new subarray (just num alone)"]
),
p('Word Break','word-break','MEDIUM',10,"Can you break a string into dictionary words? dp[i] = true if s[0..i-1] can be segmented. For each position, check all possible last words.",'Bottom-Up DP','dp[i] = can s[0..i] be segmented? For each j < i, if dp[j] and s[j..i] is in dictionary → dp[i]=true.',[{step:1,description:"s='leetcode', wordDict=['leet','code']",diagram:"dp[4]=true (leet), dp[8]=true (leet+code) ✅"}],
sol("def wordBreak(s, wordDict):\n    words = set(wordDict)\n    dp = [False] * (len(s) + 1)\n    dp[0] = True\n    for i in range(1, len(s) + 1):\n        for j in range(i):\n            if dp[j] and s[j:i] in words:\n                dp[i] = True\n                break\n    return dp[len(s)]","public boolean wordBreak(String s, List<String> wordDict) {\n    Set<String> words=new HashSet<>(wordDict);\n    boolean[] dp=new boolean[s.length()+1];\n    dp[0]=true;\n    for(int i=1;i<=s.length();i++)for(int j=0;j<i;j++)if(dp[j]&&words.contains(s.substring(j,i))){dp[i]=true;break;}\n    return dp[s.length()];\n}","bool wordBreak(string s, vector<string>& wordDict) {\n    unordered_set<string> words(wordDict.begin(),wordDict.end());\n    vector<bool> dp(s.size()+1);\n    dp[0]=true;\n    for(int i=1;i<=s.size();i++)for(int j=0;j<i;j++)if(dp[j]&&words.count(s.substr(j,i-j))){dp[i]=true;break;}\n    return dp[s.size()];\n}"),
{time:'O(n²*m)',space:'O(n)',simpleExplanation:"n² substring checks, each up to length m for hash lookup."},"WORD BREAK = dp[i] = any j where dp[j] and s[j..i] is a word. Build left to right!",
[mcq("What does dp[i] represent?",["The longest word ending at i","Whether s[0..i-1] can be segmented into dictionary words","The number of words used","Whether s[i] is a vowel"],1,"dp[i]=true means the first i characters of s can be broken into valid dictionary words.")],
["dp[0]=true (empty string is valid).","For each end position i, try all start positions j.","If dp[j] is true and s[j..i] is a word → dp[i]=true."],
["Not using a set for O(1) word lookup","Checking from right to left only"]
),
p('Longest Increasing Subsequence','longest-increasing-subsequence','MEDIUM',11,"Find the longest strictly increasing subsequence. dp[i] = length of LIS ending at index i. For each i, check all j < i: if nums[j] < nums[i], dp[i] = max(dp[i], dp[j]+1).",'DP with Binary Search optimization','O(n²) DP: dp[i] = max LIS ending at i. O(n log n): maintain sorted tails array, binary search insertion point.',[{step:1,description:"nums=[10,9,2,5,3,7,101,18]",diagram:"LIS: [2,3,7,101] or [2,5,7,101] → length 4"}],
sol("def lengthOfLIS(nums):\n    from bisect import bisect_left\n    tails = []\n    for num in nums:\n        pos = bisect_left(tails, num)\n        if pos == len(tails):\n            tails.append(num)\n        else:\n            tails[pos] = num\n    return len(tails)","public int lengthOfLIS(int[] nums) {\n    List<Integer> tails=new ArrayList<>();\n    for(int n:nums){\n        int pos=Collections.binarySearch(tails,n);\n        if(pos<0)pos=-(pos+1);\n        if(pos==tails.size())tails.add(n);\n        else tails.set(pos,n);\n    }\n    return tails.size();\n}","int lengthOfLIS(vector<int>& nums) {\n    vector<int> tails;\n    for(int n:nums){\n        auto it=lower_bound(tails.begin(),tails.end(),n);\n        if(it==tails.end())tails.push_back(n);\n        else *it=n;\n    }\n    return tails.size();\n}"),
{time:'O(n log n)',space:'O(n)',simpleExplanation:"For each element, binary search in tails = O(n log n)."},"LIS = maintain sorted tails array. Binary search to find insertion point. Length of tails = LIS length!",
[mcq("What does the tails array represent?",["The actual LIS","tails[i] = smallest possible tail of an increasing subsequence of length i+1","Sorted input","Maximum values"],1,"tails[i] stores the smallest possible ending value for an IS of length i+1. This lets us extend efficiently.")],
["Maintain an array of smallest tails for each LIS length.","Binary search for insertion point of each new element.","If > all tails → extend. Otherwise → replace to keep tails small."],
["O(n²) DP when O(n log n) is possible","Not understanding that tails array isn't the actual LIS"]
),
p('Partition Equal Subset Sum','partition-equal-subset-sum','MEDIUM',12,"Can you split array into two subsets with equal sum? Target = totalSum/2. It's a 0/1 knapsack: can we reach target using some elements? dp[j] = can we make sum j?",'0/1 Knapsack DP','If total is odd → false. Target = total/2. dp[j] = can we make sum j. For each num, update dp[j] = dp[j] || dp[j-num].',[{step:1,description:"nums=[1,5,11,5]",diagram:"Total=22, target=11. {1,5,5}=11, {11}=11 ✅"}],
sol("def canPartition(nums):\n    total = sum(nums)\n    if total % 2: return False\n    target = total // 2\n    dp = {0}\n    for num in nums:\n        dp = dp | {s + num for s in dp}\n        if target in dp: return True\n    return target in dp","public boolean canPartition(int[] nums) {\n    int total=0;for(int n:nums)total+=n;\n    if(total%2!=0)return false;\n    int target=total/2;\n    boolean[] dp=new boolean[target+1];\n    dp[0]=true;\n    for(int n:nums)for(int j=target;j>=n;j--)dp[j]=dp[j]||dp[j-n];\n    return dp[target];\n}","bool canPartition(vector<int>& nums) {\n    int total=0;for(int n:nums)total+=n;\n    if(total%2)return false;\n    int target=total/2;\n    vector<bool> dp(target+1);\n    dp[0]=true;\n    for(int n:nums)for(int j=target;j>=n;j--)dp[j]=dp[j]||dp[j-n];\n    return dp[target];\n}"),
{time:'O(n*sum)',space:'O(sum)',simpleExplanation:"n elements, each update dp array of size sum/2."},"EQUAL PARTITION = 0/1 Knapsack. Target = total/2. Can we fill the knapsack exactly?",
[mcq("Why check if total is odd first?",["Odd total can't be split into two equal integer sums","Odd numbers are harder","It's for performance","Convention"],0,"If total is odd, total/2 isn't an integer, so equal partition is impossible. Quick early return!")],
["If total is odd → impossible.","Target = total/2. Use knapsack DP.","dp[j] = can we make sum j using available numbers."],
["Not checking if total is odd first","Iterating j forward instead of backward (would use same element twice)"]
),
]);

// ==================== 2D DP (abbreviated - 5 key problems) ====================
console.log('\n📊 2D Dynamic Programming');
await seed('2d-dynamic-programming',[
p('Unique Paths','unique-paths','MEDIUM',1,"Count paths from top-left to bottom-right in a grid, moving only right or down. dp[i][j] = dp[i-1][j] + dp[i][j-1]. Each cell is reachable from above or from the left.",'Grid DP','dp[i][j] = paths to reach (i,j) = paths from above + paths from left.',[{step:1,description:"m=3, n=3",diagram:"dp=[[1,1,1],[1,2,3],[1,3,6]]. Answer: 6"}],
sol("def uniquePaths(m, n):\n    dp = [1] * n\n    for _ in range(1, m):\n        for j in range(1, n):\n            dp[j] += dp[j-1]\n    return dp[-1]","public int uniquePaths(int m, int n) {\n    int[] dp=new int[n];Arrays.fill(dp,1);\n    for(int i=1;i<m;i++)for(int j=1;j<n;j++)dp[j]+=dp[j-1];\n    return dp[n-1];\n}","int uniquePaths(int m, int n) {\n    vector<int> dp(n,1);\n    for(int i=1;i<m;i++)for(int j=1;j<n;j++)dp[j]+=dp[j-1];\n    return dp[n-1];\n}"),
{time:'O(m*n)',space:'O(n)',simpleExplanation:"Fill m*n grid. Optimize to O(n) with 1D array."},"UNIQUE PATHS = dp[i][j] = dp[above] + dp[left]. First row and column are all 1s.",
[mcq("Why is the first row all 1s?",["There's only one way to reach any cell in the first row — go right","It's a convention","The formula requires it","First row is the boundary"],0,"From (0,0), you can only move right to reach (0,1), (0,2), etc. Only one path each.")],
["Each cell: paths = from above + from left.","First row and column: only 1 path (all right or all down).","Optimize space: only need previous row → 1D array."],
["Not initializing first row/column to 1","Using 2D array when 1D suffices"]
),
p('Longest Common Subsequence','longest-common-subsequence','MEDIUM',2,"Find the longest subsequence common to two strings. dp[i][j] = LCS of s1[0..i-1] and s2[0..j-1]. If chars match: dp[i-1][j-1]+1. If not: max(dp[i-1][j], dp[i][j-1]).",'2D DP Table','dp[i][j] = LCS length for first i chars of s1 and first j chars of s2. Match → diagonal+1. No match → max(up, left).',[{step:1,description:"s1='abcde', s2='ace'",diagram:"LCS = 'ace', length = 3"}],
sol("def longestCommonSubsequence(text1, text2):\n    m, n = len(text1), len(text2)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if text1[i-1] == text2[j-1]:\n                dp[i][j] = dp[i-1][j-1] + 1\n            else:\n                dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    return dp[m][n]","public int longestCommonSubsequence(String a, String b) {\n    int m=a.length(),n=b.length();\n    int[][] dp=new int[m+1][n+1];\n    for(int i=1;i<=m;i++)for(int j=1;j<=n;j++)\n        dp[i][j]=a.charAt(i-1)==b.charAt(j-1)?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);\n    return dp[m][n];\n}","int longestCommonSubsequence(string a, string b) {\n    int m=a.size(),n=b.size();\n    vector<vector<int>> dp(m+1,vector<int>(n+1));\n    for(int i=1;i<=m;i++)for(int j=1;j<=n;j++)\n        dp[i][j]=a[i-1]==b[j-1]?dp[i-1][j-1]+1:max(dp[i-1][j],dp[i][j-1]);\n    return dp[m][n];\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"Fill m×n table. Each cell O(1)."},"LCS = 2D DP. Match → diagonal+1. No match → max(up, left).",
[mcq("What happens when characters match?",["Take max of up and left","Take diagonal (dp[i-1][j-1]) + 1","Add both characters","Start over"],1,"Matching characters extend the LCS by 1. We look at the LCS without either character (diagonal) and add 1.")],
["Build m×n table. Compare characters at each (i,j).","Match: dp[i-1][j-1]+1. No match: max(dp[i-1][j], dp[i][j-1]).","Answer at dp[m][n]."],
["Not adding 1 on match","Confusing subsequence (not contiguous) with substring (contiguous)"]
),
p('Best Time to Buy and Sell Stock with Cooldown','best-time-to-buy-and-sell-stock-with-cooldown','MEDIUM',3,"Buy/sell stock with 1-day cooldown after selling. State machine DP: held (holding stock), sold (just sold), rest (cooling down or idle).",'State Machine DP','Three states: hold, sold, rest. Transitions: hold→hold/sold, sold→rest, rest→rest/hold.',[{step:1,description:"prices=[1,2,3,0,2]",diagram:"Buy 1, sell 2, cooldown, buy 0, sell 2 → profit=3"}],
sol("def maxProfit(prices):\n    if not prices: return 0\n    hold, sold, rest = -prices[0], 0, 0\n    for i in range(1, len(prices)):\n        prev_hold, prev_sold, prev_rest = hold, sold, rest\n        hold = max(prev_hold, prev_rest - prices[i])\n        sold = prev_hold + prices[i]\n        rest = max(prev_rest, prev_sold)\n    return max(sold, rest)","public int maxProfit(int[] prices) {\n    int hold=-prices[0],sold=0,rest=0;\n    for(int i=1;i<prices.length;i++){\n        int ph=hold,ps=sold,pr=rest;\n        hold=Math.max(ph,pr-prices[i]);\n        sold=ph+prices[i];\n        rest=Math.max(pr,ps);\n    }\n    return Math.max(sold,rest);\n}","int maxProfit(vector<int>& prices) {\n    int hold=-prices[0],sold=0,rest=0;\n    for(int i=1;i<prices.size();i++){\n        int ph=hold,ps=sold,pr=rest;\n        hold=max(ph,pr-prices[i]);\n        sold=ph+prices[i];\n        rest=max(pr,ps);\n    }\n    return max(sold,rest);\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass, three variables."},"STOCK COOLDOWN = state machine: hold, sold, rest. Track max profit in each state!",
[mcq("What states do we track?",["Buy, sell, wait","hold (have stock), sold (just sold, must cooldown), rest (no stock, can buy)","Only profit","Current and previous"],1,"Three states capture all possibilities at each day. Transitions enforce the cooldown rule.")],
["Model as state machine: hold, sold, rest.","hold: keep holding or buy from rest. sold: sell from hold. rest: stay or receive from sold.","Answer: max(sold, rest) at the end."],
["Not modeling the cooldown state","Using a single variable instead of three states"]
),
p('Coin Change II','coin-change-ii','MEDIUM',4,"Count the number of ways to make amount using given coins (unbounded). Order doesn't matter! Process coins one at a time to avoid counting permutations.",'Unbounded Knapsack (Count Ways)','dp[j] = ways to make amount j. For each coin, for j = coin..amount: dp[j] += dp[j-coin].',[{step:1,description:"amount=5, coins=[1,2,5]",diagram:"Ways: {5}, {2,2,1}, {2,1,1,1}, {1,1,1,1,1} = 4 ways"}],
sol("def change(amount, coins):\n    dp = [0] * (amount + 1)\n    dp[0] = 1\n    for coin in coins:\n        for j in range(coin, amount + 1):\n            dp[j] += dp[j - coin]\n    return dp[amount]","public int change(int amount, int[] coins) {\n    int[] dp=new int[amount+1];\n    dp[0]=1;\n    for(int c:coins)for(int j=c;j<=amount;j++)dp[j]+=dp[j-c];\n    return dp[amount];\n}","int change(int amount, vector<int>& coins) {\n    vector<int> dp(amount+1);\n    dp[0]=1;\n    for(int c:coins)for(int j=c;j<=amount;j++)dp[j]+=dp[j-c];\n    return dp[amount];\n}"),
{time:'O(amount * coins)',space:'O(amount)',simpleExplanation:"Process each coin over the amount range."},"COIN CHANGE II = outer loop coins, inner loop amounts. This avoids counting order as different!",
[mcq("Why iterate coins in the outer loop?",["To count COMBINATIONS not permutations","It's faster","Doesn't matter","To sort the coins"],0,"If amounts were outer and coins inner, [1,2] and [2,1] would count as different ways. Coins-first ensures each combination is counted once.")],
["dp[0]=1. For each coin, update amounts from coin to target.","dp[j] += dp[j-coin] adds ways using this coin.","Outer=coins, inner=amounts → combinations, not permutations."],
["Swapping loop order (counts permutations instead of combinations)","Starting inner loop from 0 instead of coin"]
),
p('Target Sum','target-sum','MEDIUM',5,"Assign + or - to each number to reach target. Count ways. Transform: find subset with sum = (total+target)/2. It's a 0/1 knapsack counting problem!",'0/1 Knapsack (Count Subsets)','Transform: positive subset P, negative N. P-N=target, P+N=total → P=(total+target)/2. Count subsets summing to P.',[{step:1,description:"nums=[1,1,1,1,1], target=3",diagram:"5 ways: -1+1+1+1+1, +1-1+1+1+1, etc."}],
sol("def findTargetSumWays(nums, target):\n    total = sum(nums)\n    if (total + target) % 2 or abs(target) > total: return 0\n    t = (total + target) // 2\n    dp = [0] * (t + 1)\n    dp[0] = 1\n    for num in nums:\n        for j in range(t, num - 1, -1):\n            dp[j] += dp[j - num]\n    return dp[t]","public int findTargetSumWays(int[] nums, int target) {\n    int total=0;for(int n:nums)total+=n;\n    if((total+target)%2!=0||Math.abs(target)>total)return 0;\n    int t=(total+target)/2;\n    int[] dp=new int[t+1];dp[0]=1;\n    for(int n:nums)for(int j=t;j>=n;j--)dp[j]+=dp[j-n];\n    return dp[t];\n}","int findTargetSumWays(vector<int>& nums, int target) {\n    int total=0;for(int n:nums)total+=n;\n    if((total+target)%2||abs(target)>total)return 0;\n    int t=(total+target)/2;\n    vector<int> dp(t+1);dp[0]=1;\n    for(int n:nums)for(int j=t;j>=n;j--)dp[j]+=dp[j-n];\n    return dp[t];\n}"),
{time:'O(n*sum)',space:'O(sum)',simpleExplanation:"0/1 knapsack over n elements and target sum."},"TARGET SUM = transform to knapsack. P=(total+target)/2. Count subsets summing to P!",
[mcq("How does +/- assignment become a knapsack problem?",["P-N=target and P+N=total, so P=(total+target)/2. Count subsets summing to P.","It doesn't","We assign coins randomly","By sorting first"],0,"Splitting into positive set P and negative set N: P-N=target, P+N=total → P=(total+target)/2. This is a subset sum counting problem!")],
["Transform: target sum → subset sum = (total+target)/2.","Use 0/1 knapsack DP to count subsets reaching that sum.","Check: (total+target) must be even and ≥0."],
["Not doing the math transformation","Forgetting edge cases: total < |target|, odd sum"]
),
]);

// Quick seeds for remaining topics with fewer problems each
console.log('\n🏃 Greedy');
await seed('greedy',[
p('Maximum Subarray','maximum-subarray','MEDIUM',1,"Find the subarray with maximum sum. Kadane's algorithm: track current sum. If it goes negative, reset to 0. Track the global max.",'Kadane\'s Algorithm','curSum = max(num, curSum + num). If previous sum is negative, start fresh. Track max.',[{step:1,description:"nums=[-2,1,-3,4,-1,2,1,-5,4]",diagram:"Max subarray: [4,-1,2,1] = 6"}],
sol("def maxSubArray(nums):\n    curSum = maxSum = nums[0]\n    for n in nums[1:]:\n        curSum = max(n, curSum + n)\n        maxSum = max(maxSum, curSum)\n    return maxSum","public int maxSubArray(int[] nums) {\n    int cur=nums[0],max=nums[0];\n    for(int i=1;i<nums.length;i++){cur=Math.max(nums[i],cur+nums[i]);max=Math.max(max,cur);}\n    return max;\n}","int maxSubArray(vector<int>& nums) {\n    int cur=nums[0],mx=nums[0];\n    for(int i=1;i<nums.size();i++){cur=max(nums[i],cur+nums[i]);mx=max(mx,cur);}\n    return mx;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass, two variables."},"MAX SUBARRAY = Kadane's. curSum = max(num, curSum+num). Negative sum? Start fresh!",
[mcq("When do we start a new subarray?",["Every element","When curSum + num < num (extending the old subarray makes it worse than starting fresh)","At negative numbers","Never"],1,"If the running sum is negative, it would only drag down the next element. Better to start fresh.")],
["Running sum: either extend or start new.","curSum = max(num, curSum + num).","Track global maximum throughout."],
["Not handling all-negative arrays","Starting curSum at 0 instead of first element"]
),
p('Jump Game','jump-game','MEDIUM',2,"Can you reach the last index? Track the farthest reachable position. If current index > farthest, you're stuck!",'Greedy (Track Farthest)','Track maxReach. For each index ≤ maxReach, update maxReach = max(maxReach, i+nums[i]). If maxReach ≥ last index → true.',[{step:1,description:"nums=[2,3,1,1,4]",diagram:"maxReach: 2→4→4→4→4 ≥ 4 ✅"}],
sol("def canJump(nums):\n    maxReach = 0\n    for i in range(len(nums)):\n        if i > maxReach: return False\n        maxReach = max(maxReach, i + nums[i])\n    return True","public boolean canJump(int[] nums) {\n    int max=0;\n    for(int i=0;i<nums.length;i++){if(i>max)return false;max=Math.max(max,i+nums[i]);}\n    return true;\n}","bool canJump(vector<int>& nums) {\n    int mx=0;\n    for(int i=0;i<nums.size();i++){if(i>mx)return false;mx=max(mx,i+(int)nums[i]);}\n    return true;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass tracking farthest reach."},"JUMP GAME = track farthest reachable. If i > farthest → stuck. If farthest ≥ end → can reach!",
[mcq("When can we NOT reach the end?",["When any element is 0","When we reach an index beyond our farthest reachable position","When the array is too long","Never"],1,"If current index i > maxReach, no previous position could reach here. We're stuck!")],
["Track the farthest position reachable so far.","At each index, update: maxReach = max(maxReach, i + nums[i]).","If i > maxReach → can't proceed → false."],
["Checking only if last element is 0","BFS/DFS approach (works but O(n²) or worse)"]
),
]);

console.log('\n📅 Intervals');
await seed('intervals',[
p('Merge Intervals','merge-intervals','MEDIUM',1,"Sort intervals by start. Iterate: if current overlaps with last merged, extend end. Otherwise start new.",'Sort + Merge','Sort by start. For each interval: if overlaps with last in result, merge (extend end). Else add new.',[{step:1,description:"intervals=[[1,3],[2,6],[8,10],[15,18]]",diagram:"[1,3]+[2,6]→[1,6]. Result: [[1,6],[8,10],[15,18]]"}],
sol("def merge(intervals):\n    intervals.sort()\n    merged = [intervals[0]]\n    for start, end in intervals[1:]:\n        if start <= merged[-1][1]:\n            merged[-1][1] = max(merged[-1][1], end)\n        else:\n            merged.append([start, end])\n    return merged","public int[][] merge(int[][] intervals) {\n    Arrays.sort(intervals,(a,b)->a[0]-b[0]);\n    List<int[]> res=new ArrayList<>();\n    res.add(intervals[0]);\n    for(int i=1;i<intervals.length;i++){\n        if(intervals[i][0]<=res.get(res.size()-1)[1])res.get(res.size()-1)[1]=Math.max(res.get(res.size()-1)[1],intervals[i][1]);\n        else res.add(intervals[i]);\n    }\n    return res.toArray(new int[0][]);\n}","vector<vector<int>> merge(vector<vector<int>>& intervals) {\n    sort(intervals.begin(),intervals.end());\n    vector<vector<int>> res={intervals[0]};\n    for(int i=1;i<intervals.size();i++){\n        if(intervals[i][0]<=res.back()[1])res.back()[1]=max(res.back()[1],intervals[i][1]);\n        else res.push_back(intervals[i]);\n    }\n    return res;\n}"),
{time:'O(n log n)',space:'O(n)',simpleExplanation:"Sort O(n log n) + merge pass O(n)."},"MERGE INTERVALS = sort by start. Overlap (start ≤ prev end)? Extend. No overlap? New interval.",
[mcq("How to detect overlap?",["Start of current ≤ end of previous merged interval","End of current > start of previous","They share a number","Start == end"],0,"If current start ≤ last merged end, they overlap. Merge by taking max of both ends.")],
["Sort by start time.","If current overlaps with last merged → extend end.","Otherwise, start a new merged interval."],
["Not sorting first","Using <= vs < for overlap detection (problem-dependent)"]
),
]);

console.log('\n🔢 Math & Geometry');
await seed('math-geometry',[
p('Rotate Image','rotate-image','MEDIUM',1,"Rotate a matrix 90° clockwise in-place. Two steps: transpose (swap rows/columns) then reverse each row.",'Transpose + Reverse','Step 1: Transpose (swap matrix[i][j] with matrix[j][i]). Step 2: Reverse each row.',[{step:1,description:"[[1,2,3],[4,5,6],[7,8,9]]",diagram:"Transpose: [[1,4,7],[2,5,8],[3,6,9]] → Reverse rows: [[7,4,1],[8,5,2],[9,6,3]]"}],
sol("def rotate(matrix):\n    n = len(matrix)\n    for i in range(n):\n        for j in range(i+1, n):\n            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\n    for row in matrix:\n        row.reverse()","public void rotate(int[][] m) {\n    int n=m.length;\n    for(int i=0;i<n;i++)for(int j=i+1;j<n;j++){int t=m[i][j];m[i][j]=m[j][i];m[j][i]=t;}\n    for(int[] row:m){int l=0,r=n-1;while(l<r){int t=row[l];row[l]=row[r];row[r]=t;l++;r--;}}\n}","void rotate(vector<vector<int>>& m) {\n    int n=m.size();\n    for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)swap(m[i][j],m[j][i]);\n    for(auto& row:m)reverse(row.begin(),row.end());\n}"),
{time:'O(n²)',space:'O(1)',simpleExplanation:"Visit each element twice. In-place!"},"ROTATE 90° = TRANSPOSE + REVERSE ROWS. Two simple operations!",
[mcq("What does transpose do?",["Rotates 90°","Swaps rows and columns (matrix[i][j] ↔ matrix[j][i])","Reverses the matrix","Sorts diagonal"],1,"Transpose flips across the main diagonal. Combined with row reversal, it achieves 90° clockwise rotation.")],
["Step 1: Transpose (swap across diagonal).","Step 2: Reverse each row.","Result: 90° clockwise rotation!"],
["Only transposing without reversing","Reversing columns instead of rows (gives counter-clockwise)"]
),
]);

console.log('\n⚡ Bit Manipulation');
await seed('bit-manipulation',[
p('Single Number','single-number','EASY',1,"Every element appears twice except one. Find it. XOR magic: a^a=0, a^0=a. XOR all numbers together — pairs cancel out, leaving the single number!",'XOR All Elements','XOR all numbers. Pairs cancel (x^x=0). Remaining = the single number.',[{step:1,description:"nums=[4,1,2,1,2]",diagram:"4^1^2^1^2 = 4^(1^1)^(2^2) = 4^0^0 = 4 ✅"}],
sol("def singleNumber(nums):\n    result = 0\n    for n in nums:\n        result ^= n\n    return result","public int singleNumber(int[] nums) {\n    int res=0;for(int n:nums)res^=n;return res;\n}","int singleNumber(vector<int>& nums) {\n    int res=0;for(int n:nums)res^=n;return res;\n}"),
{time:'O(n)',space:'O(1)',simpleExplanation:"One pass, XOR. No extra space!"},"SINGLE NUMBER = XOR everything. Pairs vanish (x^x=0). Survivor = answer!",
[mcq("Why does XOR work here?",["XOR is commutative and x^x=0, so all pairs cancel leaving the unique element","XOR counts bits","XOR sorts numbers","It's random"],0,"XOR properties: x^x=0 (cancel), x^0=x (identity), commutative. All pairs cancel, leaving the solo!")],
["XOR has magic properties: x^x=0 and x^0=x.","XOR all numbers. Duplicates cancel.","What's left = the single number."],
["Using a hash set (works but O(n) space)","Not understanding XOR properties"]
),
p('Number of 1 Bits','number-of-1-bits','EASY',2,"Count set bits (1s) in binary. Trick: n & (n-1) removes the lowest set bit. Count how many times until n becomes 0.",'Brian Kernighan\'s Algorithm','n & (n-1) clears the lowest set bit. Count iterations until n=0 = number of 1 bits.',[{step:1,description:"n=11 (binary: 1011)",diagram:"1011 & 1010 = 1010 (count 1). 1010 & 1001 = 1000 (count 2). 1000 & 0111 = 0 (count 3). Answer: 3"}],
sol("def hammingWeight(n):\n    count = 0\n    while n:\n        n &= n - 1\n        count += 1\n    return count","public int hammingWeight(int n) {\n    int count=0;\n    while(n!=0){n&=(n-1);count++;}\n    return count;\n}","int hammingWeight(uint32_t n) {\n    int count=0;\n    while(n){n&=(n-1);count++;}\n    return count;\n}"),
{time:'O(k)',space:'O(1)',simpleExplanation:"k = number of set bits. At most 32 iterations."},"COUNT BITS = n & (n-1) clears lowest 1. Count until n=0!",
[mcq("What does n & (n-1) do?",["Adds 1 to n","Clears the lowest set bit of n","Doubles n","Flips all bits"],1,"n-1 flips all bits from the lowest 1 to the right. AND with n clears that lowest 1.")],
["n & (n-1) removes the rightmost 1 bit.","Count how many times until n becomes 0.","Each iteration = one set bit found."],
["Checking each of 32 bits individually (works but slower for sparse bits)","Not understanding n & (n-1) trick"]
),
p('Counting Bits','counting-bits','EASY',3,"Return array where ans[i] = number of 1s in binary of i, for i=0..n. DP: ans[i] = ans[i>>1] + (i&1). Right-shift removes last bit, add 1 if last bit was set.",'DP on Bits','ans[i] = ans[i/2] + (i%2). i/2 = right shift (we know its bit count). Add 1 if last bit is 1.',[{step:1,description:"n=5",diagram:"ans=[0,1,1,2,1,2] → bits of [0,1,10,11,100,101]"}],
sol("def countBits(n):\n    ans = [0] * (n + 1)\n    for i in range(1, n + 1):\n        ans[i] = ans[i >> 1] + (i & 1)\n    return ans","public int[] countBits(int n) {\n    int[] ans=new int[n+1];\n    for(int i=1;i<=n;i++)ans[i]=ans[i>>1]+(i&1);\n    return ans;\n}","vector<int> countBits(int n) {\n    vector<int> ans(n+1);\n    for(int i=1;i<=n;i++)ans[i]=ans[i>>1]+(i&1);\n    return ans;\n}"),
{time:'O(n)',space:'O(n)',simpleExplanation:"One pass, one operation per number."},"COUNTING BITS = ans[i] = ans[i>>1] + (i&1). Use previous results!",
[mcq("Why does ans[i>>1] help?",["i>>1 is i with the last bit removed — we already computed its bit count","It's faster than counting each time","i>>1 is always 0","Convention"],0,"i>>1 drops the last bit. Its popcount is known (already computed). Just check if the dropped bit was 1.")],
["ans[0]=0. For each i: ans[i] = ans[i/2] + last_bit.","i>>1 = i without last bit (already computed).","i&1 = last bit (0 or 1)."],
["Computing each number's bits from scratch (O(n*32) vs O(n))"]
),
]);

const total=await prisma.problem.count();
console.log(`\n🎉 Done! Total problems: ${total}/150`);
}
main().catch(console.error).finally(()=>prisma.$disconnect());
