import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
function p(t:string,s:string,d:'EASY'|'MEDIUM'|'HARD',o:number,story:string,pat:string,patEx:string,vs:any[],sols:any,cx:any,mem:string,quiz:any[],hints:string[],mistakes:string[]){return{title:t,slug:s,difficulty:d,order:o,story,visualSteps:JSON.stringify(vs),pattern:pat,patternExplanation:patEx,solutions:JSON.stringify(sols),complexity:JSON.stringify(cx),memoryTrick:mem,quiz:JSON.stringify(quiz),hints:JSON.stringify(hints),commonMistakes:JSON.stringify(mistakes)};}
function sol(py:string,java:string,cpp:string){return{python:{code:py,lineExplanations:py.split('\n').map(()=>'')},java:{code:java,lineExplanations:java.split('\n').map(()=>'')},cpp:{code:cpp,lineExplanations:cpp.split('\n').map(()=>'')}}}
function mcq(q:string,opts:string[],c:number,ex:string){return{type:'multiple_choice',question:q,options:opts,correct:c,explanation:ex}}
async function seedTopic(slug:string,problems:any[]){const topic=await prisma.topic.findUnique({where:{slug}});if(!topic){console.log(`Topic ${slug} not found`);return;}for(const prob of problems){const e=await prisma.problem.findUnique({where:{slug:prob.slug}});if(e){console.log(`  ⏭ ${prob.slug}`);continue;}await prisma.problem.create({data:{...prob,topicId:topic.id}});console.log(`  ✅ ${prob.slug}`);}}

async function main(){
console.log('🚀 Batch 4: Backtracking, Graphs, Advanced Graphs...\n');

// ==================== BACKTRACKING (9) ====================
console.log('🔄 Backtracking');
await seedTopic('backtracking',[
p('Subsets','subsets','MEDIUM',1,"Generate all subsets of a set. For each element, you have two choices: include it or skip it. Like a binary tree of decisions! Backtracking explores all paths.",'Backtracking (Include/Exclude)','For each element, branch: include it in current subset or don\'t. At the end, every path = one subset.',[{step:1,description:"nums=[1,2,3]",diagram:"[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]"}],
sol("def subsets(nums):\n    result = []\n    def backtrack(i, current):\n        if i == len(nums):\n            result.append(current[:])\n            return\n        current.append(nums[i])\n        backtrack(i + 1, current)\n        current.pop()\n        backtrack(i + 1, current)\n    backtrack(0, [])\n    return result","public List<List<Integer>> subsets(int[] nums) {\n    List<List<Integer>> res=new ArrayList<>();\n    backtrack(nums,0,new ArrayList<>(),res);\n    return res;\n}\nvoid backtrack(int[] nums,int i,List<Integer> cur,List<List<Integer>> res) {\n    if (i==nums.length) { res.add(new ArrayList<>(cur)); return; }\n    cur.add(nums[i]); backtrack(nums,i+1,cur,res); cur.remove(cur.size()-1);\n    backtrack(nums,i+1,cur,res);\n}","vector<vector<int>> subsets(vector<int>& nums) {\n    vector<vector<int>> res; vector<int> cur;\n    function<void(int)> bt=[&](int i){\n        if(i==nums.size()){res.push_back(cur);return;}\n        cur.push_back(nums[i]);bt(i+1);cur.pop_back();bt(i+1);\n    };\n    bt(0);return res;\n}"),
{time:'O(n*2ⁿ)',space:'O(n)',simpleExplanation:"2ⁿ subsets, each up to n elements to copy."},"SUBSETS = for each element: INCLUDE or SKIP. Binary decision tree!",
[mcq("How many subsets does a set of n elements have?",["n","n²","2ⁿ","n!"],2,"Each element is either in or out = 2 choices. n elements = 2ⁿ combinations.")],
["Each element: include or exclude. Two branches.","Base case: processed all elements → save current subset.","Backtrack: add element, recurse, remove element, recurse."],
["Not making a copy of current subset before adding to result","Forgetting to backtrack (remove element after recursion)"]
),
p('Combination Sum','combination-sum','MEDIUM',2,"Find all combinations of candidates that sum to target. Elements can be reused! Backtrack: for each candidate, either use it (stay at same index) or skip it (move to next).",'Backtracking with Reuse','Try each candidate. If sum < target, keep using it (same index). If sum == target, save result. If sum > target, backtrack.',[{step:1,description:"candidates=[2,3,6,7], target=7",diagram:"[2,2,3], [7]"}],
sol("def combinationSum(candidates, target):\n    result = []\n    def backtrack(i, current, total):\n        if total == target:\n            result.append(current[:])\n            return\n        if i >= len(candidates) or total > target:\n            return\n        current.append(candidates[i])\n        backtrack(i, current, total + candidates[i])\n        current.pop()\n        backtrack(i + 1, current, total)\n    backtrack(0, [], 0)\n    return result","public List<List<Integer>> combinationSum(int[] c, int target) {\n    List<List<Integer>> res=new ArrayList<>();\n    bt(c,0,target,new ArrayList<>(),res);\n    return res;\n}\nvoid bt(int[] c,int i,int rem,List<Integer> cur,List<List<Integer>> res){\n    if(rem==0){res.add(new ArrayList<>(cur));return;}\n    if(i>=c.length||rem<0)return;\n    cur.add(c[i]);bt(c,i,rem-c[i],cur,res);cur.remove(cur.size()-1);\n    bt(c,i+1,rem,cur,res);\n}","vector<vector<int>> combinationSum(vector<int>& c, int target) {\n    vector<vector<int>> res; vector<int> cur;\n    function<void(int,int)> bt=[&](int i,int rem){\n        if(rem==0){res.push_back(cur);return;}\n        if(i>=c.size()||rem<0)return;\n        cur.push_back(c[i]);bt(i,rem-c[i]);cur.pop_back();bt(i+1,rem);\n    };\n    bt(0,target);return res;\n}"),
{time:'O(2^t)',space:'O(t)',simpleExplanation:"Exponential combinations. Recursion depth ≈ target/min(candidate)."},"COMBO SUM = backtrack with REUSE (stay at same index) or SKIP (next index).",
[mcq("How do we allow reusing the same number?",["Sort the array","Recurse with the SAME index (not i+1)","Use a hash set","We can't"],1,"Staying at index i means we can pick candidates[i] again. Moving to i+1 skips it.")],
["Include candidate[i] and recurse with SAME index (reuse allowed).","Or skip to i+1.","Stop when sum==target (save) or sum>target (prune)."],
["Moving to i+1 after using an element (prevents reuse)","Not pruning when total > target"]
),
p('Permutations','permutations','MEDIUM',3,"Generate all orderings of a list. At each position, try every unused element. Like arranging people in a line — each seat can be any remaining person!",'Backtracking (Swap/Used Set)','For each position, try each unused element. Mark as used, recurse, unmark.',[{step:1,description:"nums=[1,2,3]",diagram:"[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]"}],
sol("def permute(nums):\n    result = []\n    def backtrack(current):\n        if len(current) == len(nums):\n            result.append(current[:])\n            return\n        for num in nums:\n            if num not in current:\n                current.append(num)\n                backtrack(current)\n                current.pop()\n    backtrack([])\n    return result","public List<List<Integer>> permute(int[] nums) {\n    List<List<Integer>> res=new ArrayList<>();\n    bt(nums,new ArrayList<>(),new boolean[nums.length],res);\n    return res;\n}\nvoid bt(int[] nums,List<Integer> cur,boolean[] used,List<List<Integer>> res){\n    if(cur.size()==nums.length){res.add(new ArrayList<>(cur));return;}\n    for(int i=0;i<nums.length;i++){\n        if(used[i])continue;\n        used[i]=true;cur.add(nums[i]);bt(nums,cur,used,res);\n        cur.remove(cur.size()-1);used[i]=false;\n    }\n}","vector<vector<int>> permute(vector<int>& nums) {\n    vector<vector<int>> res; vector<int> cur; vector<bool> used(nums.size());\n    function<void()> bt=[&](){\n        if(cur.size()==nums.size()){res.push_back(cur);return;}\n        for(int i=0;i<nums.size();i++){\n            if(used[i])continue;\n            used[i]=true;cur.push_back(nums[i]);bt();cur.pop_back();used[i]=false;\n        }\n    };\n    bt();return res;\n}"),
{time:'O(n*n!)',space:'O(n)',simpleExplanation:"n! permutations, each of length n."},"PERMUTATIONS = for each position, try all UNUSED elements. Mark, recurse, unmark!",
[mcq("How many permutations of n elements?",["2ⁿ","n²","n!","n*n"],2,"First position has n choices, second has n-1, etc. n*(n-1)*...*1 = n!")],
["At each position, try every element not yet used.","Mark as used, recurse, then unmark (backtrack).","Base case: all positions filled → save permutation."],
["Not unmarking elements after backtracking","Using subsets approach (doesn't preserve order)"]
),
p('Subsets II','subsets-ii','MEDIUM',4,"Like Subsets but with duplicates. Sort first! When skipping an element, skip ALL duplicates of it to avoid duplicate subsets.",'Backtracking + Skip Duplicates','Sort array. When choosing to skip an element, skip all identical consecutive elements.',[{step:1,description:"nums=[1,2,2]",diagram:"[],[1],[1,2],[1,2,2],[2],[2,2]"}],
sol("def subsetsWithDup(nums):\n    nums.sort()\n    result = []\n    def backtrack(i, current):\n        if i == len(nums):\n            result.append(current[:])\n            return\n        current.append(nums[i])\n        backtrack(i + 1, current)\n        current.pop()\n        while i + 1 < len(nums) and nums[i] == nums[i + 1]: i += 1\n        backtrack(i + 1, current)\n    backtrack(0, [])\n    return result","public List<List<Integer>> subsetsWithDup(int[] nums) {\n    Arrays.sort(nums);\n    List<List<Integer>> res=new ArrayList<>();\n    bt(nums,0,new ArrayList<>(),res);return res;\n}\nvoid bt(int[] nums,int i,List<Integer> cur,List<List<Integer>> res){\n    if(i==nums.length){res.add(new ArrayList<>(cur));return;}\n    cur.add(nums[i]);bt(nums,i+1,cur,res);cur.remove(cur.size()-1);\n    while(i+1<nums.length&&nums[i]==nums[i+1])i++;\n    bt(nums,i+1,cur,res);\n}","vector<vector<int>> subsetsWithDup(vector<int>& nums) {\n    sort(nums.begin(),nums.end());\n    vector<vector<int>> res; vector<int> cur;\n    function<void(int)> bt=[&](int i){\n        if(i==nums.size()){res.push_back(cur);return;}\n        cur.push_back(nums[i]);bt(i+1);cur.pop_back();\n        while(i+1<(int)nums.size()&&nums[i]==nums[i+1])i++;\n        bt(i+1);\n    };\n    bt(0);return res;\n}"),
{time:'O(n*2ⁿ)',space:'O(n)',simpleExplanation:"Same as subsets but with duplicate pruning."},"SUBSETS WITH DUPS = sort + skip consecutive duplicates when choosing to EXCLUDE.",
[mcq("Why sort the array first?",["To make it faster","So duplicates are adjacent, making them easy to skip","It's required","For better output order"],1,"Sorting groups duplicates together. When we skip an element, we skip ALL identical ones.")],
["Sort first so duplicates are adjacent.","Include/exclude like normal subsets.","When excluding, skip all consecutive duplicates."],
["Not sorting first","Skipping duplicates incorrectly (only skip 1 instead of all)"]
),
p('Combination Sum II','combination-sum-ii','MEDIUM',5,"Like Combination Sum but each number used at most once, and input has duplicates. Sort + skip duplicates at same level.",'Backtracking + No Reuse + Dedup','Sort. Use each element at most once (i+1). At same decision level, skip duplicates.',[{step:1,description:"candidates=[10,1,2,7,6,1,5], target=8",diagram:"[1,1,6],[1,2,5],[1,7],[2,6]"}],
sol("def combinationSum2(candidates, target):\n    candidates.sort()\n    result = []\n    def backtrack(i, current, total):\n        if total == target:\n            result.append(current[:])\n            return\n        for j in range(i, len(candidates)):\n            if total + candidates[j] > target: break\n            if j > i and candidates[j] == candidates[j-1]: continue\n            current.append(candidates[j])\n            backtrack(j + 1, current, total + candidates[j])\n            current.pop()\n    backtrack(0, [], 0)\n    return result","public List<List<Integer>> combinationSum2(int[] c, int target) {\n    Arrays.sort(c);\n    List<List<Integer>> res=new ArrayList<>();\n    bt(c,0,target,new ArrayList<>(),res);return res;\n}\nvoid bt(int[] c,int i,int rem,List<Integer> cur,List<List<Integer>> res){\n    if(rem==0){res.add(new ArrayList<>(cur));return;}\n    for(int j=i;j<c.length;j++){\n        if(rem-c[j]<0)break;\n        if(j>i&&c[j]==c[j-1])continue;\n        cur.add(c[j]);bt(c,j+1,rem-c[j],cur,res);cur.remove(cur.size()-1);\n    }\n}","vector<vector<int>> combinationSum2(vector<int>& c, int target) {\n    sort(c.begin(),c.end());\n    vector<vector<int>> res; vector<int> cur;\n    function<void(int,int)> bt=[&](int i,int rem){\n        if(rem==0){res.push_back(cur);return;}\n        for(int j=i;j<c.size();j++){\n            if(rem-c[j]<0)break;\n            if(j>i&&c[j]==c[j-1])continue;\n            cur.push_back(c[j]);bt(j+1,rem-c[j]);cur.pop_back();\n        }\n    };\n    bt(0,target);return res;\n}"),
{time:'O(2ⁿ)',space:'O(n)',simpleExplanation:"Exponential subsets with pruning."},"COMBO SUM II = sort + j>i && c[j]==c[j-1] → skip (dedup at same level).",
[mcq("How to avoid duplicate combinations?",["Use a set","Sort and skip c[j]==c[j-1] when j>i at same recursion level","Remove duplicates from input","Can't avoid them"],1,"At the same decision level, if we already tried value X, skip the next identical X.")],
["Sort. At each level, skip duplicates: if c[j]==c[j-1] and j>i, skip.","Use j+1 (not j) to prevent reuse.","Break early if remaining < candidate (sorted, so all after are bigger)."],
["Allowing reuse (using j instead of j+1)","Not skipping duplicates at the same level"]
),
p('Word Search','word-search','MEDIUM',6,"Find a word in a 2D grid by moving up/down/left/right. DFS from each cell matching the first letter. Mark visited cells to avoid reuse. Backtrack when path doesn't work.",'Grid DFS + Backtracking','Start DFS from each cell matching word[0]. Move in 4 directions. Mark visited. If word found → true. Backtrack on failure.',[{step:1,description:"board=[['A','B','C'],['S','F','C'],['A','D','E']], word='ABCCED'",diagram:"A→B→C→C→E→D ✅"}],
sol("def exist(board, word):\n    m, n = len(board), len(board[0])\n    def dfs(r, c, i):\n        if i == len(word): return True\n        if r<0 or r>=m or c<0 or c>=n or board[r][c] != word[i]: return False\n        board[r][c] = '#'\n        found = any(dfs(r+dr,c+dc,i+1) for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)])\n        board[r][c] = word[i]\n        return found\n    return any(dfs(r,c,0) for r in range(m) for c in range(n))","public boolean exist(char[][] board, String word) {\n    for(int r=0;r<board.length;r++)for(int c=0;c<board[0].length;c++)if(dfs(board,word,r,c,0))return true;\n    return false;\n}\nboolean dfs(char[][] b,String w,int r,int c,int i){\n    if(i==w.length())return true;\n    if(r<0||r>=b.length||c<0||c>=b[0].length||b[r][c]!=w.charAt(i))return false;\n    char tmp=b[r][c];b[r][c]='#';\n    boolean f=dfs(b,w,r+1,c,i+1)||dfs(b,w,r-1,c,i+1)||dfs(b,w,r,c+1,i+1)||dfs(b,w,r,c-1,i+1);\n    b[r][c]=tmp;return f;\n}","bool exist(vector<vector<char>>& b, string w) {\n    for(int r=0;r<b.size();r++)for(int c=0;c<b[0].size();c++)if(dfs(b,w,r,c,0))return true;\n    return false;\n}\nbool dfs(vector<vector<char>>& b,string& w,int r,int c,int i){\n    if(i==w.size())return true;\n    if(r<0||r>=(int)b.size()||c<0||c>=(int)b[0].size()||b[r][c]!=w[i])return false;\n    char tmp=b[r][c];b[r][c]='#';\n    bool f=dfs(b,w,r+1,c,i+1)||dfs(b,w,r-1,c,i+1)||dfs(b,w,r,c+1,i+1)||dfs(b,w,r,c-1,i+1);\n    b[r][c]=tmp;return f;\n}"),
{time:'O(m*n*4^L)',space:'O(L)',simpleExplanation:"Try each cell, DFS up to word length L with 4 directions."},"WORD SEARCH = DFS from each cell, mark visited '#', backtrack by restoring.",
[mcq("Why mark cells as '#'?",["To make them special","To prevent revisiting the same cell in the current path","To sort the board","It's not necessary"],1,"Without marking, we could use the same cell multiple times in one path, which isn't allowed.")],
["Start DFS from each cell matching word[0].","Move in 4 directions matching word characters.","Mark visited with '#', restore after backtracking."],
["Not restoring cells after backtracking","Not checking bounds before accessing"]
),
p('Palindrome Partitioning','palindrome-partitioning','MEDIUM',7,"Split a string into parts where every part is a palindrome. Backtrack: try every possible first palindrome, then recurse on the remaining string.",'Backtracking + Palindrome Check','Try all prefix splits. If prefix is palindrome, recurse on suffix. Collect all valid partitions.',[{step:1,description:"s='aab'",diagram:"['a','a','b'] and ['aa','b']"}],
sol("def partition(s):\n    result = []\n    def backtrack(start, current):\n        if start == len(s):\n            result.append(current[:])\n            return\n        for end in range(start + 1, len(s) + 1):\n            sub = s[start:end]\n            if sub == sub[::-1]:\n                current.append(sub)\n                backtrack(end, current)\n                current.pop()\n    backtrack(0, [])\n    return result","public List<List<String>> partition(String s) {\n    List<List<String>> res=new ArrayList<>();\n    bt(s,0,new ArrayList<>(),res);return res;\n}\nvoid bt(String s,int start,List<String> cur,List<List<String>> res){\n    if(start==s.length()){res.add(new ArrayList<>(cur));return;}\n    for(int end=start+1;end<=s.length();end++){\n        String sub=s.substring(start,end);\n        if(isPalin(sub)){cur.add(sub);bt(s,end,cur,res);cur.remove(cur.size()-1);}\n    }\n}\nboolean isPalin(String s){int l=0,r=s.length()-1;while(l<r)if(s.charAt(l++)!=s.charAt(r--))return false;return true;}","vector<vector<string>> partition(string s) {\n    vector<vector<string>> res; vector<string> cur;\n    function<void(int)> bt=[&](int start){\n        if(start==s.size()){res.push_back(cur);return;}\n        for(int end=start+1;end<=s.size();end++){\n            string sub=s.substr(start,end-start);\n            string rev(sub.rbegin(),sub.rend());\n            if(sub==rev){cur.push_back(sub);bt(end);cur.pop_back();}\n        }\n    };\n    bt(0);return res;\n}"),
{time:'O(n*2ⁿ)',space:'O(n)',simpleExplanation:"Up to 2ⁿ partitions, palindrome check O(n) each."},"PALINDROME PARTITION = try all prefix cuts. If prefix is palindrome, recurse on rest.",
[mcq("When do we add a partition to the result?",["When we find any palindrome","When we've processed the entire string (start == length)","After each palindrome check","When the last part is a palindrome"],1,"Only when ALL parts are palindromes AND we've covered the entire string (start reached the end).")],
["Try every prefix of remaining string.","If it's a palindrome, recurse on the rest.","Base case: reached end of string → all parts are palindromes, save result."],
["Not checking if each part is actually a palindrome","Forgetting the base case"]
),
p('Letter Combinations of a Phone Number','letter-combinations-of-a-phone-number','MEDIUM',8,"Map digits to letters (like old phone keypads). For each digit, try each possible letter. Backtrack to build all combinations.",'Backtracking + Digit Mapping','Map each digit to its letters. For each digit in input, try each letter and recurse.',[{step:1,description:"digits='23'",diagram:"2→'abc', 3→'def' → ['ad','ae','af','bd','be','bf','cd','ce','cf']"}],
sol("def letterCombinations(digits):\n    if not digits: return []\n    phone = {'2':'abc','3':'def','4':'ghi','5':'jkl','6':'mno','7':'pqrs','8':'tuv','9':'wxyz'}\n    result = []\n    def backtrack(i, current):\n        if i == len(digits):\n            result.append(current)\n            return\n        for letter in phone[digits[i]]:\n            backtrack(i + 1, current + letter)\n    backtrack(0, '')\n    return result","public List<String> letterCombinations(String digits) {\n    if(digits.isEmpty())return new ArrayList<>();\n    String[] phone={\"abc\",\"def\",\"ghi\",\"jkl\",\"mno\",\"pqrs\",\"tuv\",\"wxyz\"};\n    List<String> res=new ArrayList<>();\n    bt(digits,0,new StringBuilder(),phone,res);return res;\n}\nvoid bt(String d,int i,StringBuilder cur,String[] ph,List<String> res){\n    if(i==d.length()){res.add(cur.toString());return;}\n    for(char c:ph[d.charAt(i)-'2'].toCharArray()){cur.append(c);bt(d,i+1,cur,ph,res);cur.deleteCharAt(cur.length()-1);}\n}","vector<string> letterCombinations(string digits) {\n    if(digits.empty())return {};\n    string phone[]={\"abc\",\"def\",\"ghi\",\"jkl\",\"mno\",\"pqrs\",\"tuv\",\"wxyz\"};\n    vector<string> res; string cur;\n    function<void(int)> bt=[&](int i){\n        if(i==digits.size()){res.push_back(cur);return;}\n        for(char c:phone[digits[i]-'2']){cur+=c;bt(i+1);cur.pop_back();}\n    };\n    bt(0);return res;\n}"),
{time:'O(4ⁿ)',space:'O(n)',simpleExplanation:"Each digit maps to 3-4 letters. Up to 4ⁿ combinations."},"PHONE COMBOS = digit→letters mapping + backtrack through each digit's options.",
[mcq("How many combinations for 'n' digits?",["n","3ⁿ","Up to 4ⁿ (digits 7 and 9 have 4 letters)","n²"],2,"Most digits map to 3 letters, but 7→'pqrs' and 9→'wxyz' have 4. Worst case: 4ⁿ.")],
["Map each digit to its letters.","For each digit, try each letter and recurse to next digit.","Base case: processed all digits → save combination."],
["Forgetting to handle empty input","Wrong digit-to-letter mapping"]
),
p('N-Queens','n-queens','HARD',9,"Place n queens on an n×n chessboard so none attack each other. Backtrack row by row. For each row, try each column. Check: no queen in same column, same diagonal, or same anti-diagonal.",'Backtracking with Constraint Sets','Place queens row by row. Track used columns, diagonals (r-c), anti-diagonals (r+c). If safe, place and recurse.',[{step:1,description:"n=4",diagram:"['.Q..','...Q','Q...','..Q.'] and ['..Q.','Q...','...Q','.Q..']"}],
sol("def solveNQueens(n):\n    result = []\n    cols, diags, antis = set(), set(), set()\n    board = [['.']*n for _ in range(n)]\n    def backtrack(r):\n        if r == n:\n            result.append([''.join(row) for row in board])\n            return\n        for c in range(n):\n            if c in cols or (r-c) in diags or (r+c) in antis: continue\n            cols.add(c); diags.add(r-c); antis.add(r+c)\n            board[r][c] = 'Q'\n            backtrack(r + 1)\n            cols.remove(c); diags.remove(r-c); antis.remove(r+c)\n            board[r][c] = '.'\n    backtrack(0)\n    return result","public List<List<String>> solveNQueens(int n) {\n    List<List<String>> res=new ArrayList<>();\n    Set<Integer> cols=new HashSet<>(),diags=new HashSet<>(),antis=new HashSet<>();\n    char[][] board=new char[n][n];\n    for(char[] r:board)Arrays.fill(r,'.');\n    bt(0,n,cols,diags,antis,board,res);return res;\n}\nvoid bt(int r,int n,Set<Integer> cols,Set<Integer> diags,Set<Integer> antis,char[][] board,List<List<String>> res){\n    if(r==n){List<String> b=new ArrayList<>();for(char[] row:board)b.add(new String(row));res.add(b);return;}\n    for(int c=0;c<n;c++){\n        if(cols.contains(c)||diags.contains(r-c)||antis.contains(r+c))continue;\n        cols.add(c);diags.add(r-c);antis.add(r+c);board[r][c]='Q';\n        bt(r+1,n,cols,diags,antis,board,res);\n        cols.remove(c);diags.remove(r-c);antis.remove(r+c);board[r][c]='.';\n    }\n}","vector<vector<string>> solveNQueens(int n) {\n    vector<vector<string>> res;\n    unordered_set<int> cols,diags,antis;\n    vector<string> board(n,string(n,'.'));\n    function<void(int)> bt=[&](int r){\n        if(r==n){res.push_back(board);return;}\n        for(int c=0;c<n;c++){\n            if(cols.count(c)||diags.count(r-c)||antis.count(r+c))continue;\n            cols.insert(c);diags.insert(r-c);antis.insert(r+c);board[r][c]='Q';\n            bt(r+1);\n            cols.erase(c);diags.erase(r-c);antis.erase(r+c);board[r][c]='.';\n        }\n    };\n    bt(0);return res;\n}"),
{time:'O(n!)',space:'O(n²)',simpleExplanation:"At most n! placements to try. Board = O(n²)."},"N-QUEENS = row by row, track cols + diag(r-c) + anti-diag(r+c) in sets.",
[mcq("How to detect diagonal attacks?",["Check every placed queen","Queens on the same diagonal have the same (row-col) value","Diagonals can't be checked efficiently","Compare row differences"],1,"Same diagonal: r1-c1 == r2-c2. Same anti-diagonal: r1+c1 == r2+c2. Use sets for O(1) checks.")],
["Place one queen per row (guarantees no row conflicts).","For each column, check: not in used cols, diags (r-c), or anti-diags (r+c).","Place, recurse, backtrack."],
["Not checking both diagonal directions","O(n²) validation per placement instead of O(1) set lookups"]
),
]);

// ==================== GRAPHS (13) ====================
console.log('\n🕸️ Graphs');
await seedTopic('graphs',[
p('Number of Islands','number-of-islands','MEDIUM',1,"Count islands in a 2D grid of '1's (land) and '0's (water). When you find a '1', that's a new island. DFS/BFS to mark all connected '1's as visited. Count how many times you start a new search.",'DFS/BFS Grid Traversal','Iterate grid. On finding unvisited \'1\', increment count and DFS/BFS to mark all connected land as visited.',[{step:1,description:"grid=[['1','1','0'],['1','1','0'],['0','0','1']]",diagram:"Island 1: top-left 2×2 block. Island 2: bottom-right. Count=2 ✅"}],
sol("def numIslands(grid):\n    count = 0\n    m, n = len(grid), len(grid[0])\n    def dfs(r, c):\n        if r<0 or r>=m or c<0 or c>=n or grid[r][c]!='1': return\n        grid[r][c] = '0'\n        dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\n    for r in range(m):\n        for c in range(n):\n            if grid[r][c] == '1':\n                count += 1\n                dfs(r, c)\n    return count","public int numIslands(char[][] grid) {\n    int count=0;\n    for(int r=0;r<grid.length;r++)for(int c=0;c<grid[0].length;c++)if(grid[r][c]=='1'){count++;dfs(grid,r,c);}\n    return count;\n}\nvoid dfs(char[][] g,int r,int c){\n    if(r<0||r>=g.length||c<0||c>=g[0].length||g[r][c]!='1')return;\n    g[r][c]='0';dfs(g,r+1,c);dfs(g,r-1,c);dfs(g,r,c+1);dfs(g,r,c-1);\n}","int numIslands(vector<vector<char>>& grid) {\n    int count=0,m=grid.size(),n=grid[0].size();\n    function<void(int,int)> dfs=[&](int r,int c){\n        if(r<0||r>=m||c<0||c>=n||grid[r][c]!='1')return;\n        grid[r][c]='0';dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1);\n    };\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++)if(grid[r][c]=='1'){count++;dfs(r,c);}\n    return count;\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"Visit every cell once = O(m*n). Recursion stack = O(m*n) worst case."},"ISLANDS = scan grid. New '1' = new island. DFS to sink all connected '1's.",
[mcq("Why mark visited cells as '0'?",["To count them","To prevent counting the same island multiple times","To make the grid smaller","It's not necessary"],1,"Once we find an island and explore all its cells, marking them '0' ensures we don't start a new island count from a cell we already visited.")],
["Scan every cell. Found '1' → new island!","DFS/BFS to visit ALL connected '1's, mark as '0'.","Count of DFS starts = number of islands."],
["Not marking visited cells (infinite loop or double-counting)","Only checking right and down (need all 4 directions)"]
),
p('Clone Graph','clone-graph','MEDIUM',2,"Deep copy a graph. Use a hash map: old node → new node. DFS/BFS through the graph. For each node, create its clone if not yet created, then clone its neighbors.",'DFS + HashMap','HashMap maps old nodes to new clones. DFS: visit node, create clone, recursively clone all neighbors.',[{step:1,description:"Graph: 1-2, 1-4, 2-3, 3-4",diagram:"Clone all nodes and edges"}],
sol("def cloneGraph(node):\n    if not node: return None\n    clones = {}\n    def dfs(n):\n        if n in clones: return clones[n]\n        clone = Node(n.val)\n        clones[n] = clone\n        for neighbor in n.neighbors:\n            clone.neighbors.append(dfs(neighbor))\n        return clone\n    return dfs(node)","public Node cloneGraph(Node node) {\n    if(node==null)return null;\n    Map<Node,Node> map=new HashMap<>();\n    return dfs(node,map);\n}\nNode dfs(Node node,Map<Node,Node> map){\n    if(map.containsKey(node))return map.get(node);\n    Node clone=new Node(node.val);\n    map.put(node,clone);\n    for(Node n:node.neighbors)clone.neighbors.add(dfs(n,map));\n    return clone;\n}","Node* cloneGraph(Node* node) {\n    if(!node)return nullptr;\n    unordered_map<Node*,Node*> mp;\n    function<Node*(Node*)> dfs=[&](Node* n)->Node*{\n        if(mp.count(n))return mp[n];\n        auto clone=new Node(n->val);\n        mp[n]=clone;\n        for(auto nb:n->neighbors)clone->neighbors.push_back(dfs(nb));\n        return clone;\n    };\n    return dfs(node);\n}"),
{time:'O(V+E)',space:'O(V)',simpleExplanation:"Visit each node and edge once = O(V+E). Map stores V clones."},"CLONE GRAPH = DFS + HashMap(old→new). Create clone, recursively clone neighbors.",
[mcq("Why use a hash map?",["To sort nodes","To detect already-cloned nodes and reuse them (handles cycles)","To count edges","It's optional"],1,"Graphs can have cycles. The map prevents infinite recursion by returning existing clones.")],
["Map old node → new node.","DFS: if already cloned, return clone.","Otherwise create clone, recurse on neighbors."],
["Not handling cycles (infinite recursion)","Shallow copy instead of deep copy"]
),
p('Max Area of Island','max-area-of-island','MEDIUM',3,"Like Number of Islands but find the LARGEST island by area. DFS from each '1', count cells visited, track maximum.",'DFS + Count','Same as number of islands, but return cell count from each DFS. Track the maximum.',[{step:1,description:"grid=[[0,1,1],[1,1,0],[0,0,1]]",diagram:"Island 1: area=4, Island 2: area=1. Max=4 ✅"}],
sol("def maxAreaOfIsland(grid):\n    m,n=len(grid),len(grid[0])\n    def dfs(r,c):\n        if r<0 or r>=m or c<0 or c>=n or grid[r][c]!=1: return 0\n        grid[r][c]=0\n        return 1+dfs(r+1,c)+dfs(r-1,c)+dfs(r,c+1)+dfs(r,c-1)\n    return max((dfs(r,c) for r in range(m) for c in range(n)),default=0)","public int maxAreaOfIsland(int[][] grid) {\n    int max=0;\n    for(int r=0;r<grid.length;r++)for(int c=0;c<grid[0].length;c++)if(grid[r][c]==1)max=Math.max(max,dfs(grid,r,c));\n    return max;\n}\nint dfs(int[][] g,int r,int c){\n    if(r<0||r>=g.length||c<0||c>=g[0].length||g[r][c]!=1)return 0;\n    g[r][c]=0;return 1+dfs(g,r+1,c)+dfs(g,r-1,c)+dfs(g,r,c+1)+dfs(g,r,c-1);\n}","int maxAreaOfIsland(vector<vector<int>>& grid) {\n    int mx=0,m=grid.size(),n=grid[0].size();\n    function<int(int,int)> dfs=[&](int r,int c)->int{\n        if(r<0||r>=m||c<0||c>=n||grid[r][c]!=1)return 0;\n        grid[r][c]=0;return 1+dfs(r+1,c)+dfs(r-1,c)+dfs(r,c+1)+dfs(r,c-1);\n    };\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++)mx=max(mx,dfs(r,c));\n    return mx;\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"Visit every cell once = O(m*n)."},"MAX ISLAND = DFS returns cell count. Track the maximum across all islands.",
[mcq("How does this differ from Number of Islands?",["It's the same","DFS returns the count of cells instead of just marking them","We use BFS instead","We don't mark visited cells"],1,"Instead of just counting islands, we count the SIZE of each island and track the maximum.")],
["Same DFS as number of islands, but return the count of cells.","Track the maximum count across all DFS calls.",""],
["Only counting island count instead of area","Not returning area from DFS"]
),
p('Pacific Atlantic Water Flow','pacific-atlantic-water-flow','MEDIUM',4,"Water flows from high to low. Find cells that can reach both Pacific (top/left) and Atlantic (bottom/right). Reverse thinking: BFS from ocean borders UPHILL. Intersection = cells reaching both!",'Reverse BFS from Borders','BFS from Pacific border (top+left edges) going uphill. BFS from Atlantic border (bottom+right edges) going uphill. Intersection = answer.',[{step:1,description:"heights=[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]",diagram:"BFS from both oceans, find overlap"}],
sol("def pacificAtlantic(heights):\n    m,n=len(heights),len(heights[0])\n    pac,atl=set(),set()\n    def dfs(r,c,visit,prev):\n        if r<0 or r>=m or c<0 or c>=n or (r,c) in visit or heights[r][c]<prev: return\n        visit.add((r,c))\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]: dfs(r+dr,c+dc,visit,heights[r][c])\n    for c in range(n): dfs(0,c,pac,0); dfs(m-1,c,atl,0)\n    for r in range(m): dfs(r,0,pac,0); dfs(r,n-1,atl,0)\n    return list(pac & atl)","public List<List<Integer>> pacificAtlantic(int[][] heights) {\n    int m=heights.length,n=heights[0].length;\n    boolean[][] pac=new boolean[m][n],atl=new boolean[m][n];\n    for(int c=0;c<n;c++){dfs(heights,0,c,pac,0);dfs(heights,m-1,c,atl,0);}\n    for(int r=0;r<m;r++){dfs(heights,r,0,pac,0);dfs(heights,r,n-1,atl,0);}\n    List<List<Integer>> res=new ArrayList<>();\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++)if(pac[r][c]&&atl[r][c])res.add(Arrays.asList(r,c));\n    return res;\n}\nvoid dfs(int[][] h,int r,int c,boolean[][] v,int prev){\n    if(r<0||r>=h.length||c<0||c>=h[0].length||v[r][c]||h[r][c]<prev)return;\n    v[r][c]=true;dfs(h,r+1,c,v,h[r][c]);dfs(h,r-1,c,v,h[r][c]);dfs(h,r,c+1,v,h[r][c]);dfs(h,r,c-1,v,h[r][c]);\n}","vector<vector<int>> pacificAtlantic(vector<vector<int>>& h) {\n    int m=h.size(),n=h[0].size();\n    vector<vector<bool>> pac(m,vector<bool>(n)),atl(m,vector<bool>(n));\n    function<void(int,int,vector<vector<bool>>&,int)> dfs=[&](int r,int c,vector<vector<bool>>& v,int prev){\n        if(r<0||r>=m||c<0||c>=n||v[r][c]||h[r][c]<prev)return;\n        v[r][c]=true;dfs(r+1,c,v,h[r][c]);dfs(r-1,c,v,h[r][c]);dfs(r,c+1,v,h[r][c]);dfs(r,c-1,v,h[r][c]);\n    };\n    for(int c=0;c<n;c++){dfs(0,c,pac,0);dfs(m-1,c,atl,0);}\n    for(int r=0;r<m;r++){dfs(r,0,pac,0);dfs(r,n-1,atl,0);}\n    vector<vector<int>> res;\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++)if(pac[r][c]&&atl[r][c])res.push_back({r,c});\n    return res;\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"Two DFS traversals of the entire grid = O(m*n)."},"PACIFIC ATLANTIC = reverse DFS from borders UPHILL. Intersection = reaches both oceans.",
[mcq("Why DFS uphill from borders instead of downhill from each cell?",["DFS from borders: O(m*n). DFS from each cell: O(m*n * m*n)","Uphill is easier","Borders are closer","No reason"],0,"From each cell would repeat work. From borders, each cell visited at most twice (once per ocean) = O(m*n).")],
["Think in reverse: which cells can REACH the ocean (go uphill from border).","DFS from Pacific edges and Atlantic edges separately.","Cells in BOTH sets = answer."],
["DFS downhill from each cell (too slow)","Not considering both oceans separately"]
),
p('Course Schedule','course-schedule','MEDIUM',5,"Can you finish all courses? Each course has prerequisites forming a directed graph. If there's a CYCLE, you can't finish (circular dependency). Detect cycles with DFS + 3-color marking.",'Topological Sort / Cycle Detection','Build adjacency list. DFS with states: unvisited(0), visiting(1), visited(2). If we encounter a \'visiting\' node → cycle!',[{step:1,description:"numCourses=2, prerequisites=[[1,0]]",diagram:"0→1 (take 0 before 1). No cycle → true ✅"}],
sol("def canFinish(numCourses, prerequisites):\n    graph = [[] for _ in range(numCourses)]\n    for a, b in prerequisites: graph[a].append(b)\n    state = [0] * numCourses  # 0=unvisited, 1=visiting, 2=visited\n    def dfs(node):\n        if state[node] == 1: return False  # cycle!\n        if state[node] == 2: return True\n        state[node] = 1\n        for nei in graph[node]:\n            if not dfs(nei): return False\n        state[node] = 2\n        return True\n    return all(dfs(i) for i in range(numCourses))","public boolean canFinish(int n, int[][] pre) {\n    List<List<Integer>> g=new ArrayList<>();\n    for(int i=0;i<n;i++)g.add(new ArrayList<>());\n    for(int[] p:pre)g.get(p[0]).add(p[1]);\n    int[] state=new int[n];\n    for(int i=0;i<n;i++)if(!dfs(g,i,state))return false;\n    return true;\n}\nboolean dfs(List<List<Integer>> g,int node,int[] state){\n    if(state[node]==1)return false;\n    if(state[node]==2)return true;\n    state[node]=1;\n    for(int nei:g.get(node))if(!dfs(g,nei,state))return false;\n    state[node]=2;return true;\n}","bool canFinish(int n, vector<vector<int>>& pre) {\n    vector<vector<int>> g(n);\n    for(auto& p:pre)g[p[0]].push_back(p[1]);\n    vector<int> state(n,0);\n    function<bool(int)> dfs=[&](int node)->bool{\n        if(state[node]==1)return false;\n        if(state[node]==2)return true;\n        state[node]=1;\n        for(int nei:g[node])if(!dfs(nei))return false;\n        state[node]=2;return true;\n    };\n    for(int i=0;i<n;i++)if(!dfs(i))return false;\n    return true;\n}"),
{time:'O(V+E)',space:'O(V+E)',simpleExplanation:"DFS visits each node and edge once = O(V+E)."},"COURSE SCHEDULE = directed graph cycle detection. DFS with 3 states: unvisited → visiting → visited. Hit visiting = CYCLE!",
[mcq("What indicates a cycle in DFS?",["Revisiting any node","Visiting a node that's currently in the 'visiting' state (on current DFS path)","Finding a node with no edges","A node with multiple parents"],1,"A node in 'visiting' state means it's on our current path. Reaching it again = we've gone in a circle = cycle!")],
["Model as directed graph: prereq [a,b] means a→b.","DFS with 3 states: 0=white, 1=gray(in progress), 2=black(done).","Hitting a gray node = cycle → can't finish."],
["Only marking visited/unvisited (2 states can't detect cycles in directed graphs)","Wrong edge direction in the graph"]
),
p('Course Schedule II','course-schedule-ii','MEDIUM',6,"Return the ORDER to take courses (topological sort). Same cycle detection, but also record the order. When a node is fully visited, add to result. Reverse at end = topological order.",'Topological Sort (DFS Post-Order)','DFS with cycle detection. Add node to result after all dependencies visited. Reverse = valid order.',[{step:1,description:"4 courses, prereqs: [[1,0],[2,0],[3,1],[3,2]]",diagram:"Order: [0,1,2,3] or [0,2,1,3]"}],
sol("def findOrder(numCourses, prerequisites):\n    graph = [[] for _ in range(numCourses)]\n    for a, b in prerequisites: graph[a].append(b)\n    state = [0] * numCourses\n    order = []\n    def dfs(node):\n        if state[node] == 1: return False\n        if state[node] == 2: return True\n        state[node] = 1\n        for nei in graph[node]:\n            if not dfs(nei): return False\n        state[node] = 2\n        order.append(node)\n        return True\n    for i in range(numCourses):\n        if not dfs(i): return []\n    return order","public int[] findOrder(int n, int[][] pre) {\n    List<List<Integer>> g=new ArrayList<>();\n    for(int i=0;i<n;i++)g.add(new ArrayList<>());\n    for(int[] p:pre)g.get(p[0]).add(p[1]);\n    int[] state=new int[n]; List<Integer> order=new ArrayList<>();\n    for(int i=0;i<n;i++)if(!dfs(g,i,state,order))return new int[]{};\n    return order.stream().mapToInt(Integer::intValue).toArray();\n}\nboolean dfs(List<List<Integer>> g,int node,int[] state,List<Integer> order){\n    if(state[node]==1)return false;\n    if(state[node]==2)return true;\n    state[node]=1;\n    for(int nei:g.get(node))if(!dfs(g,nei,state,order))return false;\n    state[node]=2;order.add(node);return true;\n}","vector<int> findOrder(int n, vector<vector<int>>& pre) {\n    vector<vector<int>> g(n); for(auto& p:pre)g[p[0]].push_back(p[1]);\n    vector<int> state(n,0),order;\n    function<bool(int)> dfs=[&](int node)->bool{\n        if(state[node]==1)return false;\n        if(state[node]==2)return true;\n        state[node]=1;\n        for(int nei:g[node])if(!dfs(nei))return false;\n        state[node]=2;order.push_back(node);return true;\n    };\n    for(int i=0;i<n;i++)if(!dfs(i))return {};\n    return order;\n}"),
{time:'O(V+E)',space:'O(V+E)',simpleExplanation:"Same as Course Schedule I but with ordering."},"TOPO SORT = DFS post-order. After visiting all deps, add self. Reverse (or read forward if deps point backward).",
[mcq("When do we add a course to the order?",["Before visiting neighbors","After all its prerequisites are visited (post-order)","At random","When first discovered"],1,"Post-order ensures all dependencies come first in the final ordering.")],
["Same cycle detection as Course Schedule I.","Add node to result AFTER all neighbors are processed (post-order).","If cycle found → return empty array."],
["Adding nodes in pre-order instead of post-order","Not detecting cycles"]
),
p('Number of Connected Components in an Undirected Graph','number-of-connected-components-in-an-undirected-graph','MEDIUM',7,"Count connected components. Like Number of Islands but for a general graph. DFS from each unvisited node = one component.",'DFS/Union-Find','DFS from each unvisited node counts as one component. Or use Union-Find to merge connected nodes.',[{step:1,description:"n=5, edges=[[0,1],[1,2],[3,4]]",diagram:"{0,1,2} and {3,4} = 2 components"}],
sol("def countComponents(n, edges):\n    graph = [[] for _ in range(n)]\n    for a, b in edges: graph[a].append(b); graph[b].append(a)\n    visited = set()\n    count = 0\n    def dfs(node):\n        visited.add(node)\n        for nei in graph[node]:\n            if nei not in visited: dfs(nei)\n    for i in range(n):\n        if i not in visited:\n            count += 1\n            dfs(i)\n    return count","public int countComponents(int n, int[][] edges) {\n    List<List<Integer>> g=new ArrayList<>();\n    for(int i=0;i<n;i++)g.add(new ArrayList<>());\n    for(int[] e:edges){g.get(e[0]).add(e[1]);g.get(e[1]).add(e[0]);}\n    boolean[] vis=new boolean[n]; int count=0;\n    for(int i=0;i<n;i++)if(!vis[i]){count++;dfs(g,i,vis);}\n    return count;\n}\nvoid dfs(List<List<Integer>> g,int node,boolean[] vis){\n    vis[node]=true;for(int nei:g.get(node))if(!vis[nei])dfs(g,nei,vis);\n}","int countComponents(int n, vector<vector<int>>& edges) {\n    vector<vector<int>> g(n); for(auto& e:edges){g[e[0]].push_back(e[1]);g[e[1]].push_back(e[0]);}\n    vector<bool> vis(n); int count=0;\n    function<void(int)> dfs=[&](int node){vis[node]=true;for(int nei:g[node])if(!vis[nei])dfs(nei);};\n    for(int i=0;i<n;i++)if(!vis[i]){count++;dfs(i);}\n    return count;\n}"),
{time:'O(V+E)',space:'O(V+E)',simpleExplanation:"DFS visits each node and edge once."},"CONNECTED COMPONENTS = count DFS starts from unvisited nodes.",
[mcq("What's a connected component?",["A single node","A group of nodes where every pair has a path between them","A cycle","An edge"],1,"A connected component is a maximal set of nodes that are all reachable from each other.")],
["Build adjacency list. DFS from each unvisited node.","Each new DFS start = one new component.","Count the DFS starts."],
["Forgetting undirected edges go both ways","Not handling isolated nodes (no edges)"]
),
p('Rotting Oranges','rotting-oranges','MEDIUM',8,"Rotten oranges spread to adjacent fresh ones each minute. How long until all are rotten? Multi-source BFS! Start from ALL rotten oranges simultaneously. Each BFS level = 1 minute.",'Multi-Source BFS','Add all rotten oranges to queue. BFS level by level. Each level = 1 minute. Count levels until no fresh remain.',[{step:1,description:"grid=[[2,1,1],[1,1,0],[0,1,1]]",diagram:"Minute 0: 1 rotten. Minute 1-3: spreads. Minute 4: all rotten. Answer: 4 ✅"}],
sol("from collections import deque\ndef orangesRotting(grid):\n    m,n=len(grid),len(grid[0])\n    queue=deque()\n    fresh=0\n    for r in range(m):\n        for c in range(n):\n            if grid[r][c]==2: queue.append((r,c))\n            elif grid[r][c]==1: fresh+=1\n    minutes=0\n    while queue and fresh>0:\n        minutes+=1\n        for _ in range(len(queue)):\n            r,c=queue.popleft()\n            for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n                nr,nc=r+dr,c+dc\n                if 0<=nr<m and 0<=nc<n and grid[nr][nc]==1:\n                    grid[nr][nc]=2\n                    fresh-=1\n                    queue.append((nr,nc))\n    return minutes if fresh==0 else -1","public int orangesRotting(int[][] grid) {\n    Queue<int[]> q=new LinkedList<>(); int fresh=0;\n    for(int r=0;r<grid.length;r++)for(int c=0;c<grid[0].length;c++){\n        if(grid[r][c]==2)q.add(new int[]{r,c});\n        else if(grid[r][c]==1)fresh++;\n    }\n    int min=0;\n    int[][] dirs={{0,1},{0,-1},{1,0},{-1,0}};\n    while(!q.isEmpty()&&fresh>0){\n        min++;int size=q.size();\n        for(int i=0;i<size;i++){\n            int[] cell=q.poll();\n            for(int[] d:dirs){\n                int nr=cell[0]+d[0],nc=cell[1]+d[1];\n                if(nr>=0&&nr<grid.length&&nc>=0&&nc<grid[0].length&&grid[nr][nc]==1){\n                    grid[nr][nc]=2;fresh--;q.add(new int[]{nr,nc});\n                }\n            }\n        }\n    }\n    return fresh==0?min:-1;\n}","int orangesRotting(vector<vector<int>>& grid) {\n    int m=grid.size(),n=grid[0].size(),fresh=0;\n    queue<pair<int,int>> q;\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++){\n        if(grid[r][c]==2)q.push({r,c});\n        else if(grid[r][c]==1)fresh++;\n    }\n    int mins=0;\n    int dirs[]={0,1,0,-1,0};\n    while(!q.empty()&&fresh){\n        mins++;int sz=q.size();\n        for(int i=0;i<sz;i++){\n            auto[r,c]=q.front();q.pop();\n            for(int d=0;d<4;d++){\n                int nr=r+dirs[d],nc=c+dirs[d+1];\n                if(nr>=0&&nr<m&&nc>=0&&nc<n&&grid[nr][nc]==1){grid[nr][nc]=2;fresh--;q.push({nr,nc});}\n            }\n        }\n    }\n    return fresh?-1:mins;\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"BFS visits every cell at most once = O(m*n)."},"ROTTING = multi-source BFS from ALL rotten. Each BFS level = 1 minute. Return -1 if fresh remain.",
[mcq("Why multi-source BFS?",["All rotten oranges spread simultaneously, not one at a time","Single-source is faster","We can only BFS from one source","To avoid cycles"],0,"All rotten oranges start spreading at the same time. Multi-source BFS = add ALL of them to the queue initially.")],
["Count fresh oranges. Add all rotten to queue.","BFS level by level (each level = 1 minute).","After BFS, if fresh > 0 → return -1."],
["Using DFS instead of BFS (can't track time levels)","Starting BFS from only one rotten orange","Forgetting to check if all fresh oranges were reached"]
),
p('Walls and Gates','walls-and-gates','MEDIUM',9,"Fill each empty room with distance to nearest gate. Multi-source BFS from all gates simultaneously! Each BFS level adds 1 to distance.",'Multi-Source BFS from Gates','Add all gates (value 0) to queue. BFS outward. Each level increments distance by 1. First visit = shortest distance.',[{step:1,description:"INF=2147483647, grid has gates(0), walls(-1), rooms(INF)",diagram:"BFS from gates fills rooms with shortest distances"}],
sol("from collections import deque\ndef wallsAndGates(rooms):\n    if not rooms: return\n    m,n=len(rooms),len(rooms[0])\n    queue=deque()\n    for r in range(m):\n        for c in range(n):\n            if rooms[r][c]==0: queue.append((r,c))\n    while queue:\n        r,c=queue.popleft()\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            nr,nc=r+dr,c+dc\n            if 0<=nr<m and 0<=nc<n and rooms[nr][nc]==2147483647:\n                rooms[nr][nc]=rooms[r][c]+1\n                queue.append((nr,nc))","public void wallsAndGates(int[][] rooms) {\n    int m=rooms.length,n=rooms[0].length;\n    Queue<int[]> q=new LinkedList<>();\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++)if(rooms[r][c]==0)q.add(new int[]{r,c});\n    int[][] dirs={{0,1},{0,-1},{1,0},{-1,0}};\n    while(!q.isEmpty()){\n        int[] cell=q.poll();\n        for(int[] d:dirs){\n            int nr=cell[0]+d[0],nc=cell[1]+d[1];\n            if(nr>=0&&nr<m&&nc>=0&&nc<n&&rooms[nr][nc]==Integer.MAX_VALUE){\n                rooms[nr][nc]=rooms[cell[0]][cell[1]]+1;q.add(new int[]{nr,nc});\n            }\n        }\n    }\n}","void wallsAndGates(vector<vector<int>>& rooms) {\n    int m=rooms.size(),n=rooms[0].size();\n    queue<pair<int,int>> q;\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++)if(rooms[r][c]==0)q.push({r,c});\n    int dirs[]={0,1,0,-1,0};\n    while(!q.empty()){\n        auto[r,c]=q.front();q.pop();\n        for(int d=0;d<4;d++){\n            int nr=r+dirs[d],nc=c+dirs[d+1];\n            if(nr>=0&&nr<m&&nc>=0&&nc<n&&rooms[nr][nc]==INT_MAX){\n                rooms[nr][nc]=rooms[r][c]+1;q.push({nr,nc});\n            }\n        }\n    }\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"BFS from all gates visits each cell at most once."},"WALLS & GATES = multi-source BFS from gates. First visit = shortest distance.",
[mcq("Why BFS and not DFS for shortest distance?",["BFS explores level by level = shortest distance guaranteed","DFS is slower","DFS uses more memory","No difference"],0,"BFS guarantees first visit is the shortest path. DFS might find a longer path first.")],
["Add all gates to queue (multi-source).","BFS outward: each step adds 1 to distance.","Only visit INF cells (unvisited rooms)."],
["Using DFS (doesn't guarantee shortest path)","BFS from each gate separately (slower, O(gates*m*n))"]
),
p('Redundant Connection','redundant-connection','MEDIUM',10,"Find the extra edge that creates a cycle in a tree. Use Union-Find! Process edges one by one. If both nodes are already connected (same root), that edge is redundant.",'Union-Find','Process edges. Union-Find: if find(a) == find(b), the edge (a,b) creates a cycle → that\'s the redundant one.',[{step:1,description:"edges=[[1,2],[1,3],[2,3]]",diagram:"1-2, 1-3 form tree. 2-3 creates cycle → redundant!"}],
sol("def findRedundantConnection(edges):\n    parent = list(range(len(edges) + 1))\n    rank = [0] * (len(edges) + 1)\n    def find(x):\n        while parent[x] != x: parent[x] = parent[parent[x]]; x = parent[x]\n        return x\n    def union(a, b):\n        pa, pb = find(a), find(b)\n        if pa == pb: return False\n        if rank[pa] < rank[pb]: pa, pb = pb, pa\n        parent[pb] = pa\n        if rank[pa] == rank[pb]: rank[pa] += 1\n        return True\n    for a, b in edges:\n        if not union(a, b): return [a, b]","public int[] findRedundantConnection(int[][] edges) {\n    int n=edges.length;\n    int[] parent=new int[n+1],rank=new int[n+1];\n    for(int i=0;i<=n;i++)parent[i]=i;\n    for(int[] e:edges)if(!union(e[0],e[1],parent,rank))return e;\n    return new int[]{};\n}\nint find(int x,int[] p){while(p[x]!=x){p[x]=p[p[x]];x=p[x];}return x;}\nboolean union(int a,int b,int[] p,int[] r){\n    int pa=find(a,p),pb=find(b,p);\n    if(pa==pb)return false;\n    if(r[pa]<r[pb]){int t=pa;pa=pb;pb=t;}\n    p[pb]=pa;if(r[pa]==r[pb])r[pa]++;return true;\n}","vector<int> findRedundantConnection(vector<vector<int>>& edges) {\n    int n=edges.size();\n    vector<int> parent(n+1),rank(n+1,0);\n    iota(parent.begin(),parent.end(),0);\n    function<int(int)> find=[&](int x)->int{while(parent[x]!=x){parent[x]=parent[parent[x]];x=parent[x];}return x;};\n    for(auto& e:edges){\n        int pa=find(e[0]),pb=find(e[1]);\n        if(pa==pb)return e;\n        if(rank[pa]<rank[pb])swap(pa,pb);\n        parent[pb]=pa;if(rank[pa]==rank[pb])rank[pa]++;\n    }\n    return {};\n}"),
{time:'O(n α(n)) ≈ O(n)',space:'O(n)',simpleExplanation:"Union-Find with path compression + rank = nearly O(n)."},"REDUNDANT EDGE = Union-Find. If find(a)==find(b) before union → cycle → redundant!",
[mcq("When is an edge redundant?",["When it connects two already-connected nodes","When it's the longest edge","When it creates a leaf","When both nodes have degree > 1"],0,"If both endpoints are already in the same component, adding this edge creates a cycle — it's redundant.")],
["Process edges one by one with Union-Find.","If find(a) == find(b) → already connected → this edge is the answer.","Union-Find with path compression for efficiency."],
["Processing edges in wrong order","Not using path compression (slower)"]
),
p('Graph Valid Tree','graph-valid-tree','MEDIUM',11,"A valid tree has n nodes, n-1 edges, and is connected. Check: edges == n-1 AND graph is connected (DFS reaches all nodes).",'Edge Count + Connectivity Check','A tree with n nodes has exactly n-1 edges and is connected. Check both conditions.',[{step:1,description:"n=5, edges=[[0,1],[0,2],[0,3],[1,4]]",diagram:"4 edges = 5-1 ✅, connected ✅ → valid tree!"}],
sol("def validTree(n, edges):\n    if len(edges) != n - 1: return False\n    graph = [[] for _ in range(n)]\n    for a, b in edges: graph[a].append(b); graph[b].append(a)\n    visited = set()\n    def dfs(node):\n        visited.add(node)\n        for nei in graph[node]:\n            if nei not in visited: dfs(nei)\n    dfs(0)\n    return len(visited) == n","public boolean validTree(int n, int[][] edges) {\n    if(edges.length!=n-1)return false;\n    List<List<Integer>> g=new ArrayList<>();\n    for(int i=0;i<n;i++)g.add(new ArrayList<>());\n    for(int[] e:edges){g.get(e[0]).add(e[1]);g.get(e[1]).add(e[0]);}\n    boolean[] vis=new boolean[n];\n    dfs(g,0,vis);\n    for(boolean v:vis)if(!v)return false;\n    return true;\n}\nvoid dfs(List<List<Integer>> g,int node,boolean[] vis){vis[node]=true;for(int nei:g.get(node))if(!vis[nei])dfs(g,nei,vis);}","bool validTree(int n, vector<vector<int>>& edges) {\n    if((int)edges.size()!=n-1)return false;\n    vector<vector<int>> g(n);\n    for(auto& e:edges){g[e[0]].push_back(e[1]);g[e[1]].push_back(e[0]);}\n    vector<bool> vis(n);\n    function<void(int)> dfs=[&](int node){vis[node]=true;for(int nei:g[node])if(!vis[nei])dfs(nei);};\n    dfs(0);\n    for(bool v:vis)if(!v)return false;\n    return true;\n}"),
{time:'O(V+E)',space:'O(V+E)',simpleExplanation:"Edge count check O(1) + DFS O(V+E)."},"VALID TREE = exactly n-1 edges + fully connected. Check both!",
[mcq("Why check edges == n-1?",["Trees always have n-1 edges. Fewer = disconnected. More = cycle.","It's a convention","Trees can have any number of edges","To balance the tree"],0,"A tree with n nodes always has exactly n-1 edges. This is a fundamental property.")],
["Quick check: edges must equal n-1.","Then verify connectivity: DFS from node 0, check all nodes visited.","Both conditions = valid tree."],
["Only checking one condition","Forgetting directed vs undirected"]
),
p('Word Ladder','word-ladder','HARD',12,"Transform one word to another by changing one letter at a time, each step must be a valid word. Shortest path = BFS! Each word is a node, edges connect words that differ by one letter.",'BFS Shortest Path','BFS from beginWord. At each level, try changing each character to a-z. If resulting word is in wordList, add to queue. First time we reach endWord = shortest.',[{step:1,description:"beginWord='hit', endWord='cog', wordList=['hot','dot','dog','lot','log','cog']",diagram:"hit→hot→dot→dog→cog = 5 steps ✅"}],
sol("from collections import deque\ndef ladderLength(beginWord, endWord, wordList):\n    wordSet = set(wordList)\n    if endWord not in wordSet: return 0\n    queue = deque([(beginWord, 1)])\n    visited = {beginWord}\n    while queue:\n        word, steps = queue.popleft()\n        for i in range(len(word)):\n            for c in 'abcdefghijklmnopqrstuvwxyz':\n                newWord = word[:i] + c + word[i+1:]\n                if newWord == endWord: return steps + 1\n                if newWord in wordSet and newWord not in visited:\n                    visited.add(newWord)\n                    queue.append((newWord, steps + 1))\n    return 0","public int ladderLength(String begin, String end, List<String> wordList) {\n    Set<String> words=new HashSet<>(wordList);\n    if(!words.contains(end))return 0;\n    Queue<String> q=new LinkedList<>();q.add(begin);\n    Set<String> vis=new HashSet<>();vis.add(begin);\n    int steps=1;\n    while(!q.isEmpty()){\n        int size=q.size();steps++;\n        for(int i=0;i<size;i++){\n            char[] w=q.poll().toCharArray();\n            for(int j=0;j<w.length;j++){\n                char orig=w[j];\n                for(char c='a';c<='z';c++){\n                    w[j]=c;String nw=new String(w);\n                    if(nw.equals(end))return steps;\n                    if(words.contains(nw)&&!vis.contains(nw)){vis.add(nw);q.add(nw);}\n                }\n                w[j]=orig;\n            }\n        }\n    }\n    return 0;\n}","int ladderLength(string begin, string end, vector<string>& wordList) {\n    unordered_set<string> words(wordList.begin(),wordList.end());\n    if(!words.count(end))return 0;\n    queue<string> q;q.push(begin);\n    unordered_set<string> vis;vis.insert(begin);\n    int steps=1;\n    while(!q.empty()){\n        int sz=q.size();steps++;\n        for(int i=0;i<sz;i++){\n            string w=q.front();q.pop();\n            for(int j=0;j<w.size();j++){\n                char orig=w[j];\n                for(char c='a';c<='z';c++){\n                    w[j]=c;\n                    if(w==end)return steps;\n                    if(words.count(w)&&!vis.count(w)){vis.insert(w);q.push(w);}\n                }\n                w[j]=orig;\n            }\n        }\n    }\n    return 0;\n}"),
{time:'O(n*m*26)',space:'O(n*m)',simpleExplanation:"n words, m chars each, try 26 replacements = O(n*m*26)."},"WORD LADDER = BFS. Each word = node. Edge = differ by 1 letter. BFS = shortest path!",
[mcq("Why BFS and not DFS?",["BFS finds shortest path, DFS might find a longer one first","DFS is too slow","BFS uses less memory","No difference"],0,"BFS explores level by level. First time it reaches endWord = guaranteed shortest transformation.")],
["Model as graph: words connected if they differ by 1 letter.","BFS from beginWord. Try all 26 char replacements at each position.","First time endWord is reached = shortest path."],
["Using DFS (not guaranteed shortest)","Not using a visited set (infinite loops)","Building full adjacency list upfront (slow for large dictionaries)"]
),
p('Number of Islands (DFS variant)','surrounded-regions','MEDIUM',13,"Capture regions: flip all 'O's to 'X's except those connected to borders. DFS from border 'O's first (mark as safe). Then flip all remaining 'O's to 'X'. Restore safe ones.",'Border DFS + Flip','DFS from all border \'O\'s, mark as safe. Then scan grid: remaining O→X, safe→O.',[{step:1,description:"board=[['X','X','X','X'],['X','O','O','X'],['X','X','O','X'],['X','O','X','X']]",diagram:"Inner O's get captured (→X). Border-connected O stays."}],
sol("def solve(board):\n    m,n=len(board),len(board[0])\n    def dfs(r,c):\n        if r<0 or r>=m or c<0 or c>=n or board[r][c]!='O': return\n        board[r][c]='S'\n        dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1)\n    for r in range(m):\n        dfs(r,0);dfs(r,n-1)\n    for c in range(n):\n        dfs(0,c);dfs(m-1,c)\n    for r in range(m):\n        for c in range(n):\n            if board[r][c]=='O': board[r][c]='X'\n            elif board[r][c]=='S': board[r][c]='O'","public void solve(char[][] board) {\n    int m=board.length,n=board[0].length;\n    for(int r=0;r<m;r++){dfs(board,r,0);dfs(board,r,n-1);}\n    for(int c=0;c<n;c++){dfs(board,0,c);dfs(board,m-1,c);}\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++){\n        if(board[r][c]=='O')board[r][c]='X';\n        else if(board[r][c]=='S')board[r][c]='O';\n    }\n}\nvoid dfs(char[][] b,int r,int c){\n    if(r<0||r>=b.length||c<0||c>=b[0].length||b[r][c]!='O')return;\n    b[r][c]='S';dfs(b,r+1,c);dfs(b,r-1,c);dfs(b,r,c+1);dfs(b,r,c-1);\n}","void solve(vector<vector<char>>& board) {\n    int m=board.size(),n=board[0].size();\n    function<void(int,int)> dfs=[&](int r,int c){\n        if(r<0||r>=m||c<0||c>=n||board[r][c]!='O')return;\n        board[r][c]='S';dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1);\n    };\n    for(int r=0;r<m;r++){dfs(r,0);dfs(r,n-1);}\n    for(int c=0;c<n;c++){dfs(0,c);dfs(m-1,c);}\n    for(int r=0;r<m;r++)for(int c=0;c<n;c++){\n        if(board[r][c]=='O')board[r][c]='X';\n        else if(board[r][c]=='S')board[r][c]='O';\n    }\n}"),
{time:'O(m*n)',space:'O(m*n)',simpleExplanation:"DFS from borders + one grid scan = O(m*n)."},"SURROUNDED = save border-connected O's first (mark 'S'). Then O→X, S→O.",
[mcq("Why start from borders?",["Border O's can never be captured — they touch the edge","Borders are easier to process","It's required","To find the largest region"],0,"Border-connected O's escape capture. Mark them safe first, then everything else gets flipped.")],
["DFS from all border 'O's, mark as 'S' (safe).","Scan grid: remaining 'O' → 'X' (captured). 'S' → 'O' (restored).","Three-phase approach: mark safe, capture, restore."],
["Trying to capture from inside out","Not restoring safe cells"]
),
]);

const total=await prisma.problem.count();
console.log(`\n🎉 Done! Total problems: ${total}/150`);
}
main().catch(console.error).finally(()=>prisma.$disconnect());
