import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

function p(t:string,s:string,d:'EASY'|'MEDIUM'|'HARD',o:number,story:string,pat:string,patEx:string,vs:any[],sols:any,cx:any,mem:string,quiz:any[],hints:string[],mistakes:string[]) {
  return {title:t,slug:s,difficulty:d,order:o,story,visualSteps:JSON.stringify(vs),pattern:pat,patternExplanation:patEx,solutions:JSON.stringify(sols),complexity:JSON.stringify(cx),memoryTrick:mem,quiz:JSON.stringify(quiz),hints:JSON.stringify(hints),commonMistakes:JSON.stringify(mistakes)};
}
function sol(py:string,java:string,cpp:string) {
  return {python:{code:py,lineExplanations:py.split('\n').map(()=>'')},java:{code:java,lineExplanations:java.split('\n').map(()=>'')},cpp:{code:cpp,lineExplanations:cpp.split('\n').map(()=>'')}};
}
function mcq(q:string,opts:string[],c:number,ex:string){return{type:'multiple_choice',question:q,options:opts,correct:c,explanation:ex};}

async function seedTopic(slug:string,problems:any[]) {
  const topic = await prisma.topic.findUnique({where:{slug}});
  if(!topic){console.log(`Topic ${slug} not found`);return;}
  for(const prob of problems) {
    const existing = await prisma.problem.findUnique({where:{slug:prob.slug}});
    if(existing){console.log(`  ⏭ ${prob.slug}`);continue;}
    await prisma.problem.create({data:{...prob,topicId:topic.id}});
    console.log(`  ✅ ${prob.slug}`);
  }
}

async function main() {
  console.log('🚀 Seeding Batch 3: Trees, Tries, Heap, Backtracking, Graphs...\n');

  // ==================== TREES (15) ====================
  console.log('🌳 Trees');
  await seedTopic('trees', [
    p('Invert Binary Tree','invert-binary-tree','EASY',1,
      "Flip a tree like a mirror! Every left child becomes the right and vice versa. Recursively swap left and right children of every node. The famous problem that got a developer rejected from Google!",
      'Recursive Swap','Swap left and right children at each node, then recurse on both subtrees.',
      [{step:1,description:"Tree: 4(2(1,3),7(6,9))",diagram:"Swap children of 4: 4(7,2)"},{step:2,description:"Recurse: swap children of 7 and 2",diagram:"4(7(9,6),2(3,1)) ✅"}],
      sol("def invertTree(root):\n    if not root: return None\n    root.left, root.right = root.right, root.left\n    invertTree(root.left)\n    invertTree(root.right)\n    return root",
        "public TreeNode invertTree(TreeNode root) {\n    if (root==null) return null;\n    TreeNode tmp=root.left;\n    root.left=root.right;\n    root.right=tmp;\n    invertTree(root.left);\n    invertTree(root.right);\n    return root;\n}",
        "TreeNode* invertTree(TreeNode* root) {\n    if (!root) return nullptr;\n    swap(root->left, root->right);\n    invertTree(root->left);\n    invertTree(root->right);\n    return root;\n}"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node once = O(n). Recursion depth = tree height O(h)."},
      "INVERT TREE = swap left↔right at every node. 3 lines of code!",
      [mcq("What's the base case?",["Node is a leaf","Node is null","Node has one child","Tree is balanced"],1,"When we reach null, there's nothing to swap. Return null.")],
      ["Mirror image = swap left and right at every node.","Recursion: swap, then recurse on both children.","Base case: null node → return null."],
      ["Only swapping at the root level","Forgetting the base case (null check)"]
    ),
    p('Maximum Depth of Binary Tree','maximum-depth-of-binary-tree','EASY',2,
      "How tall is the tree? The depth is 1 + max(left depth, right depth). A null tree has depth 0. A single node has depth 1. Recurse down both sides, take the bigger one!",
      'Recursive Depth','maxDepth(node) = 1 + max(maxDepth(left), maxDepth(right)). Base case: null → 0.',
      [{step:1,description:"Tree: 3(9, 20(15,7))",diagram:"Left depth=1, Right depth=2"},{step:2,description:"Max depth = 1 + max(1,2) = 3",diagram:"Answer: 3 ✅"}],
      sol("def maxDepth(root):\n    if not root: return 0\n    return 1 + max(maxDepth(root.left), maxDepth(root.right))",
        "public int maxDepth(TreeNode root) {\n    if (root==null) return 0;\n    return 1+Math.max(maxDepth(root.left), maxDepth(root.right));\n}",
        "int maxDepth(TreeNode* root) {\n    if (!root) return 0;\n    return 1+max(maxDepth(root->left), maxDepth(root->right));\n}"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node = O(n). Stack depth = height O(h)."},
      "TREE DEPTH = 1 + max(left, right). Null = 0. One liner!",
      [mcq("What does maxDepth return for a null node?",["1","-1","0","undefined"],2,"Null means no node, so depth is 0. This is the base case.")],
      ["Depth = number of nodes on longest root-to-leaf path.","Recurse: 1 + max of left and right depths.","Base case: null → 0."],
      ["Returning 1 for null instead of 0","Not counting the root node"]
    ),
    p('Diameter of Binary Tree','diameter-of-binary-tree','EASY',3,
      "The diameter is the longest path between ANY two nodes (not necessarily through root). At each node, the diameter through it = left height + right height. Track the global maximum while computing heights!",
      'Height + Global Max','Compute height recursively. At each node, update global max with leftHeight + rightHeight. Return height for parent.',
      [{step:1,description:"Tree: 1(2(4,5),3)",diagram:"At node 2: left=1, right=1, diameter=2"},{step:2,description:"Global max diameter = 3 (path: 4→2→1→3)",diagram:"Answer: 3 ✅"}],
      sol("def diameterOfBinaryTree(root):\n    diameter = [0]\n    def height(node):\n        if not node: return 0\n        left = height(node.left)\n        right = height(node.right)\n        diameter[0] = max(diameter[0], left + right)\n        return 1 + max(left, right)\n    height(root)\n    return diameter[0]",
        "class Solution {\n    int diameter = 0;\n    public int diameterOfBinaryTree(TreeNode root) {\n        height(root); return diameter;\n    }\n    int height(TreeNode node) {\n        if (node==null) return 0;\n        int l=height(node.left), r=height(node.right);\n        diameter=Math.max(diameter, l+r);\n        return 1+Math.max(l,r);\n    }\n}",
        "class Solution {\n    int dia=0;\npublic:\n    int diameterOfBinaryTree(TreeNode* root) { height(root); return dia; }\n    int height(TreeNode* n) {\n        if(!n) return 0;\n        int l=height(n->left), r=height(n->right);\n        dia=max(dia, l+r);\n        return 1+max(l,r);\n    }\n};"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node = O(n). Recursion stack = O(h)."},
      "DIAMETER = leftHeight + rightHeight at each node. Track global max while computing heights!",
      [mcq("Does the diameter always pass through the root?",["Yes","No — it can be in a subtree","Only in balanced trees","Always"],1,"The longest path might be entirely in a subtree. That's why we check at every node.")],
      ["Diameter through a node = left_height + right_height.","Compute heights recursively, update global max at each node.","Return the global max, not the root's value."],
      ["Only checking diameter through the root","Confusing diameter (edges) with depth (nodes)"]
    ),
    p('Balanced Binary Tree','balanced-binary-tree','EASY',4,
      "A balanced tree means for EVERY node, the height difference between left and right subtrees is at most 1. Check recursively: compute height, but return -1 if any subtree is unbalanced.",
      'Height with Early Termination','Compute height recursively. If |leftH - rightH| > 1, return -1 to signal imbalance. Propagate -1 upward.',
      [{step:1,description:"Tree: 1(2(3(4,null),null),2)",diagram:"Node 2: leftH=2, rightH=0, diff=2 > 1 → unbalanced!"}],
      sol("def isBalanced(root):\n    def height(node):\n        if not node: return 0\n        left = height(node.left)\n        right = height(node.right)\n        if left == -1 or right == -1 or abs(left - right) > 1:\n            return -1\n        return 1 + max(left, right)\n    return height(root) != -1",
        "public boolean isBalanced(TreeNode root) {\n    return height(root) != -1;\n}\nint height(TreeNode node) {\n    if (node==null) return 0;\n    int l=height(node.left), r=height(node.right);\n    if (l==-1||r==-1||Math.abs(l-r)>1) return -1;\n    return 1+Math.max(l,r);\n}",
        "bool isBalanced(TreeNode* root) { return height(root)!=-1; }\nint height(TreeNode* n) {\n    if(!n) return 0;\n    int l=height(n->left), r=height(n->right);\n    if(l==-1||r==-1||abs(l-r)>1) return -1;\n    return 1+max(l,r);\n}"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Single pass checking height + balance = O(n)."},
      "BALANCED = height check + return -1 as 'unbalanced' signal. One pass, O(n)!",
      [mcq("Why return -1 instead of a boolean?",["It's faster","We need the height value AND the balanced status — -1 encodes 'unbalanced' while allowing height propagation","Convention","No reason"],1,"-1 serves double duty: signals imbalance AND short-circuits further computation.")],
      ["At every node, check if |leftHeight - rightHeight| ≤ 1.","Naive: O(n²) checking height at each node. Optimized: return -1 for unbalanced.","Propagate -1 upward to short-circuit."],
      ["Checking balance only at root","O(n²) approach: calling height() separately for each node"]
    ),
    p('Same Tree','same-tree','EASY',5,
      "Two trees are the same if they have identical structure AND values. Compare recursively: both null → same. One null → different. Values differ → different. Otherwise check both subtrees.",
      'Recursive Comparison','Compare node by node. Both null=true, one null=false, vals differ=false, else recurse on left and right.',
      [{step:1,description:"Tree1: 1(2,3) vs Tree2: 1(2,3)",diagram:"Same structure, same values ✅"}],
      sol("def isSameTree(p, q):\n    if not p and not q: return True\n    if not p or not q: return False\n    return p.val == q.val and isSameTree(p.left, q.left) and isSameTree(p.right, q.right)",
        "public boolean isSameTree(TreeNode p, TreeNode q) {\n    if (p==null&&q==null) return true;\n    if (p==null||q==null) return false;\n    return p.val==q.val && isSameTree(p.left,q.left) && isSameTree(p.right,q.right);\n}",
        "bool isSameTree(TreeNode* p, TreeNode* q) {\n    if(!p&&!q) return true;\n    if(!p||!q) return false;\n    return p->val==q->val && isSameTree(p->left,q->left) && isSameTree(p->right,q->right);\n}"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node in both trees = O(n)."},
      "SAME TREE = both null→true, one null→false, vals equal + recurse both sides.",
      [mcq("What if both nodes are null?",["Return false","Return true","Check parent","Error"],1,"Both null means both trees ended at the same point — they're identical in that subtree.")],
      ["Compare structure AND values simultaneously.","Both null = same. One null = different. Different values = different.","Recurse on left pair and right pair."],
      ["Only checking values, not structure","Not handling the both-null base case"]
    ),
    p('Subtree of Another Tree','subtree-of-another-tree','EASY',6,
      "Is tree t a subtree of tree s? At every node of s, check: does this subtree match t exactly (using Same Tree)? It's like searching for a pattern in a bigger picture.",
      'Traverse + Same Tree Check','For each node in s, check if the subtree rooted there equals t (using isSameTree). Return true if any match.',
      [{step:1,description:"s=3(4(1,2),5), t=4(1,2)",diagram:"At node 4: isSameTree(4(1,2), 4(1,2)) = true ✅"}],
      sol("def isSubtree(root, subRoot):\n    if not root: return False\n    if isSameTree(root, subRoot): return True\n    return isSubtree(root.left, subRoot) or isSubtree(root.right, subRoot)\ndef isSameTree(p, q):\n    if not p and not q: return True\n    if not p or not q: return False\n    return p.val == q.val and isSameTree(p.left, q.left) and isSameTree(p.right, q.right)",
        "public boolean isSubtree(TreeNode root, TreeNode sub) {\n    if (root==null) return false;\n    if (isSame(root,sub)) return true;\n    return isSubtree(root.left,sub)||isSubtree(root.right,sub);\n}\nboolean isSame(TreeNode a, TreeNode b) {\n    if (a==null&&b==null) return true;\n    if (a==null||b==null) return false;\n    return a.val==b.val&&isSame(a.left,b.left)&&isSame(a.right,b.right);\n}",
        "bool isSubtree(TreeNode* s, TreeNode* t) {\n    if(!s) return false;\n    if(isSame(s,t)) return true;\n    return isSubtree(s->left,t)||isSubtree(s->right,t);\n}\nbool isSame(TreeNode* a, TreeNode* b) {\n    if(!a&&!b) return true;\n    if(!a||!b) return false;\n    return a->val==b->val&&isSame(a->left,b->left)&&isSame(a->right,b->right);\n}"),
      {time:'O(m*n)',space:'O(h)',simpleExplanation:"For each of m nodes in s, compare with t (n nodes) = O(m*n)."},
      "SUBTREE = for each node in s, check isSameTree with t. Found match → true!",
      [mcq("What's the time complexity?",["O(n)","O(m+n)","O(m*n)","O(log n)"],2,"At each of m nodes in s, we might compare all n nodes of t. Worst case O(m*n).")],
      ["At each node of s, check if it matches t exactly.","Use the Same Tree algorithm as a helper.","Recurse through s trying each node as potential root."],
      ["Only checking at the root of s","Not using a proper same-tree comparison"]
    ),
    p('Lowest Common Ancestor of BST','lowest-common-ancestor-of-a-binary-search-tree','MEDIUM',7,
      "In a BST, the LCA of two nodes is where they 'split' — one goes left, one goes right. If both are smaller, go left. Both bigger, go right. Otherwise, you're at the LCA!",
      'BST Property Exploitation','In BST: if both nodes < current → go left. Both > current → go right. Otherwise, current IS the LCA (split point).',
      [{step:1,description:"BST: 6(2(0,4(3,5)),8(7,9)), find LCA of 2 and 8",diagram:"At 6: 2<6 and 8>6 → split! LCA=6 ✅"}],
      sol("def lowestCommonAncestor(root, p, q):\n    while root:\n        if p.val < root.val and q.val < root.val:\n            root = root.left\n        elif p.val > root.val and q.val > root.val:\n            root = root.right\n        else:\n            return root",
        "public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n    while (root!=null) {\n        if (p.val<root.val&&q.val<root.val) root=root.left;\n        else if (p.val>root.val&&q.val>root.val) root=root.right;\n        else return root;\n    }\n    return null;\n}",
        "TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {\n    while (root) {\n        if (p->val<root->val&&q->val<root->val) root=root->left;\n        else if (p->val>root->val&&q->val>root->val) root=root->right;\n        else return root;\n    }\n    return nullptr;\n}"),
      {time:'O(h)',space:'O(1)',simpleExplanation:"Walk down the tree = O(h). No extra space!"},
      "BST LCA = walk down. Both left → go left. Both right → go right. Split → that's the LCA!",
      [mcq("Why is this O(h) instead of O(n)?",["We skip subtrees using BST ordering","We use a hash map","We sort the tree first","It's always O(n)"],0,"BST property lets us go directly left or right — we never visit both subtrees.")],
      ["BST property: left < parent < right. Use this!","If both targets are smaller → go left. Both bigger → go right.","Otherwise you're at the split point = LCA!"],
      ["Using the generic tree LCA algorithm (O(n) instead of O(h))","Not leveraging BST ordering"]
    ),
    p('Binary Tree Level Order Traversal','binary-tree-level-order-traversal','MEDIUM',8,
      "Visit the tree level by level, left to right — like reading a book. Use a queue (BFS)! Start with root. For each level, process all nodes in the queue, add their children. Each level becomes a list.",
      'BFS with Queue','Use a queue. Process level by level: dequeue all nodes at current level, enqueue their children. Collect values per level.',
      [{step:1,description:"Tree: 3(9, 20(15,7))",diagram:"Level 0: [3], Level 1: [9,20], Level 2: [15,7]"}],
      sol("from collections import deque\ndef levelOrder(root):\n    if not root: return []\n    result = []\n    queue = deque([root])\n    while queue:\n        level = []\n        for _ in range(len(queue)):\n            node = queue.popleft()\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result",
        "public List<List<Integer>> levelOrder(TreeNode root) {\n    List<List<Integer>> res=new ArrayList<>();\n    if (root==null) return res;\n    Queue<TreeNode> q=new LinkedList<>();\n    q.add(root);\n    while (!q.isEmpty()) {\n        List<Integer> level=new ArrayList<>();\n        int size=q.size();\n        for (int i=0;i<size;i++) {\n            TreeNode node=q.poll();\n            level.add(node.val);\n            if (node.left!=null) q.add(node.left);\n            if (node.right!=null) q.add(node.right);\n        }\n        res.add(level);\n    }\n    return res;\n}",
        "vector<vector<int>> levelOrder(TreeNode* root) {\n    vector<vector<int>> res;\n    if (!root) return res;\n    queue<TreeNode*> q;\n    q.push(root);\n    while (!q.empty()) {\n        vector<int> level;\n        int size=q.size();\n        for (int i=0;i<size;i++) {\n            auto node=q.front(); q.pop();\n            level.push_back(node->val);\n            if (node->left) q.push(node->left);\n            if (node->right) q.push(node->right);\n        }\n        res.push_back(level);\n    }\n    return res;\n}"),
      {time:'O(n)',space:'O(n)',simpleExplanation:"Visit every node = O(n). Queue holds at most one level ≈ O(n/2) = O(n)."},
      "LEVEL ORDER = BFS with queue. Process all nodes at current level, enqueue children. Capture each level as a list!",
      [mcq("Why save queue size before the inner loop?",["Performance","The queue size changes as we add children — we only want to process the current level's nodes","It's not necessary","To prevent infinite loop"],1,"As we process nodes, we add their children to the queue. Saving the size ensures we only process THIS level's nodes.")],
      ["BFS = queue. Process level by level.","Save level size, process that many nodes, enqueue children.","Each iteration of the outer loop = one level."],
      ["Not saving queue size (mixing levels)","Forgetting null check on root"]
    ),
    p('Binary Tree Right Side View','binary-tree-right-side-view','MEDIUM',9,
      "What would you see looking at the tree from the right side? The rightmost node at each level! Use level-order traversal, but only keep the last node of each level.",
      'BFS — Last Node Per Level','Level order traversal. The last node processed in each level is the rightmost = visible from the right side.',
      [{step:1,description:"Tree: 1(2(null,5),3(null,4))",diagram:"Level 0: last=1, Level 1: last=3, Level 2: last=4"}],
      sol("from collections import deque\ndef rightSideView(root):\n    if not root: return []\n    result = []\n    queue = deque([root])\n    while queue:\n        for i in range(len(queue)):\n            node = queue.popleft()\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(node.val)\n    return result",
        "public List<Integer> rightSideView(TreeNode root) {\n    List<Integer> res=new ArrayList<>();\n    if (root==null) return res;\n    Queue<TreeNode> q=new LinkedList<>(); q.add(root);\n    while (!q.isEmpty()) {\n        int size=q.size(); TreeNode node=null;\n        for (int i=0;i<size;i++) {\n            node=q.poll();\n            if (node.left!=null) q.add(node.left);\n            if (node.right!=null) q.add(node.right);\n        }\n        res.add(node.val);\n    }\n    return res;\n}",
        "vector<int> rightSideView(TreeNode* root) {\n    vector<int> res;\n    if (!root) return res;\n    queue<TreeNode*> q; q.push(root);\n    while (!q.empty()) {\n        int size=q.size(); TreeNode* node;\n        for (int i=0;i<size;i++) {\n            node=q.front(); q.pop();\n            if (node->left) q.push(node->left);\n            if (node->right) q.push(node->right);\n        }\n        res.push_back(node->val);\n    }\n    return res;\n}"),
      {time:'O(n)',space:'O(n)',simpleExplanation:"BFS visits every node = O(n)."},
      "RIGHT SIDE VIEW = BFS, take the LAST node of each level.",
      [mcq("Could you also solve this with DFS?",["No, only BFS works","Yes — visit right subtree first, track depth, first node at each new depth is the rightmost","DFS can't track levels","Only with extra data structures"],1,"DFS right-first: the first node visited at each depth is the rightmost. Both approaches work!")],
      ["Level order traversal, but we only need the last node per level.","BFS: process each level, record the last node.","Or DFS right-first: first visit at each depth = right side view."],
      ["Taking the first node instead of the last per level","Not handling single-child nodes"]
    ),
    p('Count Good Nodes in Binary Tree','count-good-nodes-in-binary-tree','MEDIUM',10,
      "A node is 'good' if no node on the path from root to it has a greater value. Track the maximum value seen so far on the path. If current node >= max, it's good! Update max and recurse.",
      'DFS with Path Maximum','Track max value from root to current node. If node.val >= maxSoFar, it\'s a good node. Update max and recurse.',
      [{step:1,description:"Tree: 3(1(3),4(1,5))",diagram:"Good: 3(root), 3(left-left, 3≥3), 4(4≥3), 5(5≥4) = 4 good nodes"}],
      sol("def goodNodes(root):\n    def dfs(node, max_val):\n        if not node: return 0\n        good = 1 if node.val >= max_val else 0\n        max_val = max(max_val, node.val)\n        return good + dfs(node.left, max_val) + dfs(node.right, max_val)\n    return dfs(root, root.val)",
        "public int goodNodes(TreeNode root) {\n    return dfs(root, root.val);\n}\nint dfs(TreeNode node, int maxVal) {\n    if (node==null) return 0;\n    int good = node.val>=maxVal ? 1 : 0;\n    maxVal = Math.max(maxVal, node.val);\n    return good + dfs(node.left,maxVal) + dfs(node.right,maxVal);\n}",
        "int goodNodes(TreeNode* root) { return dfs(root, root->val); }\nint dfs(TreeNode* n, int mx) {\n    if(!n) return 0;\n    int good = n->val>=mx ? 1 : 0;\n    mx = max(mx, n->val);\n    return good + dfs(n->left,mx) + dfs(n->right,mx);\n}"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node = O(n). Recursion = O(h)."},
      "GOOD NODE = node.val ≥ max on path from root. DFS tracking pathMax!",
      [mcq("Is the root always a good node?",["No","Yes — no ancestor has a greater value (there are no ancestors)","Only if it's the largest","Depends on children"],1,"The root has no ancestors, so no value can be greater. It's always good!")],
      ["Track the maximum value on the path from root to current.","If current >= max, it's good.","DFS with maxSoFar parameter."],
      ["Not including the root as a good node","Using global max instead of path max"]
    ),
    p('Validate Binary Search Tree','validate-binary-search-tree','MEDIUM',11,
      "A valid BST has: left subtree all < node, right subtree all > node. Pass min/max bounds down! Each node must be within (min, max). Left child gets (min, node.val), right gets (node.val, max).",
      'Recursive with Bounds','Pass allowed range (min, max) down. Node must be in range. Left child range: (min, node.val). Right: (node.val, max).',
      [{step:1,description:"Tree: 5(1,4(3,6))",diagram:"Node 4 in right subtree of 5 but 4<5 → INVALID ❌"}],
      sol("def isValidBST(root):\n    def validate(node, lo, hi):\n        if not node: return True\n        if node.val <= lo or node.val >= hi: return False\n        return validate(node.left, lo, node.val) and validate(node.right, node.val, hi)\n    return validate(root, float('-inf'), float('inf'))",
        "public boolean isValidBST(TreeNode root) {\n    return validate(root, Long.MIN_VALUE, Long.MAX_VALUE);\n}\nboolean validate(TreeNode node, long lo, long hi) {\n    if (node==null) return true;\n    if (node.val<=lo||node.val>=hi) return false;\n    return validate(node.left,lo,node.val)&&validate(node.right,node.val,hi);\n}",
        "bool isValidBST(TreeNode* root) { return v(root, LONG_MIN, LONG_MAX); }\nbool v(TreeNode* n, long lo, long hi) {\n    if(!n) return true;\n    if(n->val<=lo||n->val>=hi) return false;\n    return v(n->left,lo,n->val)&&v(n->right,n->val,hi);\n}"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node = O(n). Recursion = O(h)."},
      "VALID BST = pass (min, max) bounds. Left gets (min, node), right gets (node, max). Violate bounds → invalid!",
      [mcq("Why not just check node.left < node < node.right?",["That only checks immediate children, not the entire subtree","It's slower","It works fine","BST doesn't require that"],0,"5(4(3,6)) passes immediate checks (4<5, 3<4, 6>4) but 6 is in 5's left subtree and 6>5. Need global bounds!")],
      ["A BST requires ALL nodes in left subtree < parent, not just immediate child.","Pass min/max bounds down the recursion.","Left child inherits (min, parent.val), right inherits (parent.val, max)."],
      ["Only checking immediate children (misses subtree violations)","Using <= instead of < (BST typically means strictly less)","Integer overflow with bounds"]
    ),
    p('Kth Smallest Element in a BST','kth-smallest-element-in-a-bst','MEDIUM',12,
      "In a BST, inorder traversal visits nodes in sorted order! So the kth smallest = the kth node visited during inorder traversal. Count as you go, stop at k.",
      'Inorder Traversal','BST inorder = sorted order. Do inorder traversal, count nodes visited. When count == k, that\'s the answer!',
      [{step:1,description:"BST: 3(1(null,2),4), k=1",diagram:"Inorder: 1,2,3,4 → 1st smallest = 1 ✅"}],
      sol("def kthSmallest(root, k):\n    stack = []\n    curr = root\n    while stack or curr:\n        while curr:\n            stack.append(curr)\n            curr = curr.left\n        curr = stack.pop()\n        k -= 1\n        if k == 0: return curr.val\n        curr = curr.right",
        "public int kthSmallest(TreeNode root, int k) {\n    Stack<TreeNode> stack=new Stack<>();\n    TreeNode curr=root;\n    while (!stack.isEmpty()||curr!=null) {\n        while (curr!=null) { stack.push(curr); curr=curr.left; }\n        curr=stack.pop();\n        k--;\n        if (k==0) return curr.val;\n        curr=curr.right;\n    }\n    return -1;\n}",
        "int kthSmallest(TreeNode* root, int k) {\n    stack<TreeNode*> st;\n    TreeNode* curr=root;\n    while (!st.empty()||curr) {\n        while (curr) { st.push(curr); curr=curr->left; }\n        curr=st.top(); st.pop();\n        if (--k==0) return curr->val;\n        curr=curr->right;\n    }\n    return -1;\n}"),
      {time:'O(h+k)',space:'O(h)',simpleExplanation:"Go to leftmost = O(h), then visit k nodes = O(h+k)."},
      "KTH SMALLEST in BST = INORDER TRAVERSAL. BST inorder = sorted! Stop at k.",
      [mcq("Why does inorder traversal on a BST give sorted order?",["Coincidence","By definition: left < parent < right, so visiting left-parent-right is ascending","It only works for balanced BSTs","It doesn't always work"],1,"Inorder visits left subtree (smaller), then parent, then right (larger). This naturally produces ascending order in a BST.")],
      ["BST inorder = sorted order. Use this property!","Iterative inorder with a stack. Count down k.","When k reaches 0, current node is the answer."],
      ["Using preorder or postorder instead of inorder","Visiting all nodes when we only need k"]
    ),
    p('Construct Binary Tree from Preorder and Inorder','construct-binary-tree-from-preorder-and-inorder-traversal','MEDIUM',13,
      "Preorder: root is always first. Inorder: root splits left and right subtrees. Find root in inorder → everything left of it = left subtree, right = right subtree. Recurse!",
      'Recursive Split','Preorder[0] = root. Find root in inorder → left portion = left subtree, right = right subtree. Recurse with sliced arrays.',
      [{step:1,description:"preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]",diagram:"Root=3, left=[9], right=[15,20,7]"}],
      sol("def buildTree(preorder, inorder):\n    if not preorder: return None\n    root = TreeNode(preorder[0])\n    mid = inorder.index(preorder[0])\n    root.left = buildTree(preorder[1:mid+1], inorder[:mid])\n    root.right = buildTree(preorder[mid+1:], inorder[mid+1:])\n    return root",
        "public TreeNode buildTree(int[] preorder, int[] inorder) {\n    Map<Integer,Integer> map=new HashMap<>();\n    for (int i=0;i<inorder.length;i++) map.put(inorder[i],i);\n    return build(preorder,0,preorder.length-1,inorder,0,inorder.length-1,map);\n}\nTreeNode build(int[] pre,int ps,int pe,int[] in,int is,int ie,Map<Integer,Integer> map) {\n    if (ps>pe) return null;\n    TreeNode root=new TreeNode(pre[ps]);\n    int mid=map.get(pre[ps]);\n    int leftSize=mid-is;\n    root.left=build(pre,ps+1,ps+leftSize,in,is,mid-1,map);\n    root.right=build(pre,ps+leftSize+1,pe,in,mid+1,ie,map);\n    return root;\n}",
        "TreeNode* buildTree(vector<int>& preorder, vector<int>& inorder) {\n    unordered_map<int,int> mp;\n    for (int i=0;i<inorder.size();i++) mp[inorder[i]]=i;\n    return build(preorder,0,preorder.size()-1,inorder,0,inorder.size()-1,mp);\n}\nTreeNode* build(vector<int>&pre,int ps,int pe,vector<int>&in,int is2,int ie,unordered_map<int,int>&mp) {\n    if (ps>pe) return nullptr;\n    auto root=new TreeNode(pre[ps]);\n    int mid=mp[pre[ps]], leftSize=mid-is2;\n    root->left=build(pre,ps+1,ps+leftSize,in,is2,mid-1,mp);\n    root->right=build(pre,ps+leftSize+1,pe,in,mid+1,ie,mp);\n    return root;\n}"),
      {time:'O(n)',space:'O(n)',simpleExplanation:"Visit each node once = O(n). HashMap for O(1) lookups."},
      "CONSTRUCT TREE = preorder gives ROOT, inorder gives LEFT/RIGHT split. Recurse!",
      [mcq("What does finding the root in inorder tell us?",["Nothing","Everything left of it belongs to the left subtree, everything right to the right subtree","The tree height","The next root"],1,"Inorder is: [left subtree] ROOT [right subtree]. Finding root partitions the arrays.")],
      ["Preorder first element = root.","Find root in inorder → left portion = left subtree.","Use left subtree size to split preorder. Recurse."],
      ["O(n²) from linear search in inorder (use a hashmap instead)","Wrong index calculations when splitting preorder"]
    ),
    p('Binary Tree Maximum Path Sum','binary-tree-maximum-path-sum','HARD',14,
      "Find the maximum sum path in a tree (any node to any node). At each node, the path through it = node + left gain + right gain. Track global max. Return max single-side gain to parent.",
      'DFS with Global Max','At each node: leftGain = max(0, left). rightGain = max(0, right). Update global max with node+leftGain+rightGain. Return node+max(leftGain,rightGain) to parent.',
      [{step:1,description:"Tree: -10(9, 20(15,7))",diagram:"Path 15→20→7 = 42. But also check 9→-10→20→15 = 34. Max = 42 ✅"}],
      sol("def maxPathSum(root):\n    result = [float('-inf')]\n    def dfs(node):\n        if not node: return 0\n        left = max(0, dfs(node.left))\n        right = max(0, dfs(node.right))\n        result[0] = max(result[0], node.val + left + right)\n        return node.val + max(left, right)\n    dfs(root)\n    return result[0]",
        "class Solution {\n    int maxSum = Integer.MIN_VALUE;\n    public int maxPathSum(TreeNode root) { dfs(root); return maxSum; }\n    int dfs(TreeNode node) {\n        if (node==null) return 0;\n        int left=Math.max(0,dfs(node.left));\n        int right=Math.max(0,dfs(node.right));\n        maxSum=Math.max(maxSum,node.val+left+right);\n        return node.val+Math.max(left,right);\n    }\n}",
        "class Solution {\n    int mx=INT_MIN;\npublic:\n    int maxPathSum(TreeNode* root) { dfs(root); return mx; }\n    int dfs(TreeNode* n) {\n        if(!n) return 0;\n        int l=max(0,dfs(n->left)), r=max(0,dfs(n->right));\n        mx=max(mx,n->val+l+r);\n        return n->val+max(l,r);\n    }\n};"),
      {time:'O(n)',space:'O(h)',simpleExplanation:"Visit every node = O(n). Recursion = O(h)."},
      "MAX PATH SUM = at each node, full path = left+node+right (update global max). Return single side = node+max(left,right) to parent.",
      [mcq("Why max(0, child gain)?",["To ignore negative paths — they'd only reduce the sum","Gains can't be negative","It's a convention","To prevent overflow"],0,"If a subtree has negative gain, it's better to not include it at all (take 0 instead).")],
      ["At each node, consider the path going through it: left + node + right.","Use max(0, subtreeGain) to optionally skip negative paths.","Return single-path gain to parent (can't split both ways going up)."],
      ["Returning the full path (left+node+right) to parent instead of single side","Not handling negative values","Forgetting max(0, gain) to skip negative subtrees"]
    ),
    p('Serialize and Deserialize Binary Tree','serialize-and-deserialize-binary-tree','HARD',15,
      "Convert a tree to a string and back. Use preorder traversal with null markers. Serialize: preorder, write 'null' for empty nodes. Deserialize: read values in order, rebuild recursively.",
      'Preorder with Null Markers','Serialize with preorder, marking nulls. Deserialize by reading values sequentially and recursively building the tree.',
      [{step:1,description:"Tree: 1(2,3(4,5))",diagram:"Serialized: '1,2,null,null,3,4,null,null,5,null,null'"}],
      sol("class Codec:\n    def serialize(self, root):\n        vals = []\n        def dfs(node):\n            if not node:\n                vals.append('null')\n                return\n            vals.append(str(node.val))\n            dfs(node.left)\n            dfs(node.right)\n        dfs(root)\n        return ','.join(vals)\n    def deserialize(self, data):\n        vals = iter(data.split(','))\n        def dfs():\n            val = next(vals)\n            if val == 'null': return None\n            node = TreeNode(int(val))\n            node.left = dfs()\n            node.right = dfs()\n            return node\n        return dfs()",
        "public class Codec {\n    public String serialize(TreeNode root) {\n        StringBuilder sb=new StringBuilder();\n        dfs(root,sb); return sb.toString();\n    }\n    void dfs(TreeNode n, StringBuilder sb) {\n        if (n==null) { sb.append(\"null,\"); return; }\n        sb.append(n.val).append(\",\");\n        dfs(n.left,sb); dfs(n.right,sb);\n    }\n    public TreeNode deserialize(String data) {\n        Queue<String> q=new LinkedList<>(Arrays.asList(data.split(\",\")));\n        return build(q);\n    }\n    TreeNode build(Queue<String> q) {\n        String val=q.poll();\n        if (val.equals(\"null\")) return null;\n        TreeNode n=new TreeNode(Integer.parseInt(val));\n        n.left=build(q); n.right=build(q);\n        return n;\n    }\n}",
        "class Codec {\npublic:\n    string serialize(TreeNode* root) {\n        if(!root) return \"null,\";\n        return to_string(root->val)+\",\"+serialize(root->left)+serialize(root->right);\n    }\n    TreeNode* deserialize(string data) {\n        queue<string> q;\n        string s; stringstream ss(data);\n        while(getline(ss,s,',')) q.push(s);\n        return build(q);\n    }\n    TreeNode* build(queue<string>& q) {\n        string val=q.front(); q.pop();\n        if(val==\"null\") return nullptr;\n        auto n=new TreeNode(stoi(val));\n        n->left=build(q); n->right=build(q);\n        return n;\n    }\n};"),
      {time:'O(n)',space:'O(n)',simpleExplanation:"Visit every node once for both serialize and deserialize = O(n)."},
      "SERIALIZE = preorder + null markers. DESERIALIZE = read preorder values, rebuild recursively.",
      [mcq("Why include null markers?",["Style preference","Without nulls, we can't distinguish different tree structures that have the same values","To pad the string","They're not needed"],1,"Trees 1(2,null) and 1(null,2) have the same preorder [1,2] without nulls. Null markers make the encoding unique.")],
      ["Preorder: root, left subtree, right subtree.","Mark null nodes explicitly so structure is preserved.","Deserialize: read values in order, recursively build left then right."],
      ["Not marking null nodes (ambiguous deserialization)","Using level-order (harder to implement correctly)"]
    ),
  ]);

  // ==================== TRIES (3) ====================
  console.log('\n📖 Tries');
  await seedTopic('tries', [
    p('Implement Trie','implement-trie-prefix-tree','MEDIUM',1,
      "A Trie is a tree where each edge is a letter. To insert 'apple': a→p→p→l→e, mark e as end. To search: follow letters. To startsWith: same but don't need end marker. Like autocomplete!",
      'Trie Data Structure','Each node has children (map of char→node) and isEnd flag. Insert: create path. Search: follow path, check isEnd. StartsWith: follow path, don\'t check isEnd.',
      [{step:1,description:"Insert 'apple', 'app'",diagram:"root→a→p→p(end)→l→e(end)"},{step:2,description:"search('app')→true, startsWith('ap')→true",diagram:"Follow path, check markers"}],
      sol("class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n    def insert(self, word):\n        node = self.root\n        for c in word:\n            if c not in node.children:\n                node.children[c] = TrieNode()\n            node = node.children[c]\n        node.is_end = True\n    def search(self, word):\n        node = self._find(word)\n        return node is not None and node.is_end\n    def startsWith(self, prefix):\n        return self._find(prefix) is not None\n    def _find(self, word):\n        node = self.root\n        for c in word:\n            if c not in node.children: return None\n            node = node.children[c]\n        return node",
        "class Trie {\n    TrieNode root=new TrieNode();\n    class TrieNode { TrieNode[] ch=new TrieNode[26]; boolean end; }\n    public void insert(String w) {\n        TrieNode n=root;\n        for (char c:w.toCharArray()) {\n            if (n.ch[c-'a']==null) n.ch[c-'a']=new TrieNode();\n            n=n.ch[c-'a'];\n        }\n        n.end=true;\n    }\n    public boolean search(String w) { TrieNode n=find(w); return n!=null&&n.end; }\n    public boolean startsWith(String p) { return find(p)!=null; }\n    TrieNode find(String w) {\n        TrieNode n=root;\n        for (char c:w.toCharArray()) {\n            if (n.ch[c-'a']==null) return null;\n            n=n.ch[c-'a'];\n        }\n        return n;\n    }\n}",
        "class Trie {\n    struct Node { Node* ch[26]={}; bool end=false; };\n    Node* root=new Node();\npublic:\n    void insert(string w) {\n        Node* n=root;\n        for (char c:w) { if(!n->ch[c-'a']) n->ch[c-'a']=new Node(); n=n->ch[c-'a']; }\n        n->end=true;\n    }\n    bool search(string w) { auto n=find(w); return n&&n->end; }\n    bool startsWith(string p) { return find(p)!=nullptr; }\n    Node* find(string w) { Node* n=root; for(char c:w){if(!n->ch[c-'a'])return nullptr;n=n->ch[c-'a'];}return n; }\n};"),
      {time:'O(m) per operation',space:'O(total chars)',simpleExplanation:"Each operation walks the word length m. Space = all characters stored."},
      "TRIE = tree of letters. Insert: create path. Search: follow path + check isEnd. Prefix: follow path only.",
      [mcq("What's the advantage of a Trie over a hash set?",["Faster lookup","Efficient prefix matching — startsWith is O(prefix length)","Less memory","Simpler code"],1,"A hash set can check exact words but can't do prefix matching efficiently. Tries excel at prefix queries!")],
      ["Each node has 26 children (one per letter) and an isEnd flag.","Insert: follow/create the path letter by letter, mark the end.","Search = follow path + check isEnd. Prefix = follow path only."],
      ["Not marking word endings (search returns true for prefixes)","Using a flat array instead of tree structure"]
    ),
    p('Design Add and Search Words','design-add-and-search-words-data-structure','MEDIUM',2,
      "Like a Trie, but search supports '.' as a wildcard matching any letter. On '.', try ALL children recursively. Regular letters follow the normal Trie path.",
      'Trie + DFS for Wildcards','Insert normally into Trie. Search: on regular char follow that child. On \'.\' try all 26 children recursively.',
      [{step:1,description:"Add 'bad','dad','mad'. Search '.ad'",diagram:"'.': try b,d,m → all have 'ad' → true ✅"}],
      sol("class WordDictionary:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\n    def addWord(self, word):\n        node = self\n        for c in word:\n            if c not in node.children: node.children[c] = WordDictionary()\n            node = node.children[c]\n        node.is_end = True\n    def search(self, word):\n        return self._search(word, 0)\n    def _search(self, word, i):\n        if i == len(word): return self.is_end\n        if word[i] == '.':\n            return any(child._search(word, i+1) for child in self.children.values())\n        if word[i] not in self.children: return False\n        return self.children[word[i]]._search(word, i+1)",
        "class WordDictionary {\n    WordDictionary[] ch=new WordDictionary[26]; boolean end;\n    public void addWord(String w) {\n        WordDictionary n=this;\n        for (char c:w.toCharArray()) { if(n.ch[c-'a']==null) n.ch[c-'a']=new WordDictionary(); n=n.ch[c-'a']; }\n        n.end=true;\n    }\n    public boolean search(String w) { return dfs(w,0); }\n    boolean dfs(String w, int i) {\n        if (i==w.length()) return end;\n        if (w.charAt(i)=='.') { for (var c:ch) if(c!=null&&c.dfs(w,i+1)) return true; return false; }\n        return ch[w.charAt(i)-'a']!=null&&ch[w.charAt(i)-'a'].dfs(w,i+1);\n    }\n}",
        "class WordDictionary {\n    struct Node { Node* ch[26]={}; bool end=false; };\n    Node* root=new Node();\npublic:\n    void addWord(string w) { auto n=root; for(char c:w){if(!n->ch[c-'a'])n->ch[c-'a']=new Node();n=n->ch[c-'a'];}n->end=true; }\n    bool search(string w) { return dfs(root,w,0); }\n    bool dfs(Node* n, string& w, int i) {\n        if(i==w.size()) return n->end;\n        if(w[i]=='.'){for(auto c:n->ch)if(c&&dfs(c,w,i+1))return true;return false;}\n        return n->ch[w[i]-'a']&&dfs(n->ch[w[i]-'a'],w,i+1);\n    }\n};"),
      {time:'O(m) normal, O(26^m) worst wildcard',space:'O(total chars)',simpleExplanation:"Normal search O(m). Wildcard '...' could explore all paths."},
      "WILDCARD TRIE = normal Trie + on '.', DFS through ALL children.",
      [mcq("What makes '.' different from regular characters?",["It matches nothing","It matches any single character, so we must try all children","It's an error","It matches multiple characters"],1,"'.' is a wildcard — we don't know which child to follow, so we try all 26 possibilities.")],
      ["Build a normal Trie for addWord.","Search: regular chars follow normal path. '.' tries ALL children.","Use DFS/recursion to handle the branching on '.' ."],
      ["Not handling '.' at the end of the word","Trying to match '.' with multiple characters instead of exactly one"]
    ),
    p('Word Search II','word-search-ii','HARD',3,
      "Find all words from a dictionary in a 2D grid. Build a Trie from the word list, then DFS from each cell through the Trie simultaneously. When you reach an end-of-word node, add it to results!",
      'Trie + Grid DFS','Build Trie from words. DFS from each cell, following Trie nodes. When Trie node isEnd → found a word! Prune visited cells.',
      [{step:1,description:"board=[['o','a','a','n'],['e','t','a','e']], words=['eat','oath']",diagram:"Trie: eat, oath. DFS finds both!"}],
      sol("def findWords(board, words):\n    trie = {}\n    for w in words:\n        node = trie\n        for c in w: node = node.setdefault(c, {})\n        node['$'] = w\n    result = []\n    m, n = len(board), len(board[0])\n    def dfs(r, c, node):\n        if '$' in node:\n            result.append(node['$'])\n            del node['$']\n        if r<0 or r>=m or c<0 or c>=n: return\n        ch = board[r][c]\n        if ch not in node: return\n        board[r][c] = '#'\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            dfs(r+dr, c+dc, node[ch])\n        board[r][c] = ch\n    for r in range(m):\n        for c in range(n):\n            dfs(r, c, trie)\n    return result",
        "class Solution {\n    List<String> res=new ArrayList<>();\n    public List<String> findWords(char[][] board, String[] words) {\n        TrieNode root=new TrieNode();\n        for (String w:words) { TrieNode n=root; for(char c:w.toCharArray()){if(n.ch[c-'a']==null)n.ch[c-'a']=new TrieNode();n=n.ch[c-'a'];}n.word=w; }\n        for (int r=0;r<board.length;r++) for(int c=0;c<board[0].length;c++) dfs(board,r,c,root);\n        return res;\n    }\n    void dfs(char[][] b,int r,int c,TrieNode n) {\n        if(r<0||r>=b.length||c<0||c>=b[0].length||b[r][c]=='#'||n.ch[b[r][c]-'a']==null) return;\n        char ch=b[r][c]; n=n.ch[ch-'a'];\n        if(n.word!=null){res.add(n.word);n.word=null;}\n        b[r][c]='#';\n        dfs(b,r+1,c,n);dfs(b,r-1,c,n);dfs(b,r,c+1,n);dfs(b,r,c-1,n);\n        b[r][c]=ch;\n    }\n    class TrieNode{TrieNode[] ch=new TrieNode[26]; String word;}\n}",
        "class Solution {\n    struct Node{Node* ch[26]={};string word;};\n    vector<string> res;\npublic:\n    vector<string> findWords(vector<vector<char>>& board, vector<string>& words) {\n        Node* root=new Node();\n        for(auto& w:words){auto n=root;for(char c:w){if(!n->ch[c-'a'])n->ch[c-'a']=new Node();n=n->ch[c-'a'];}n->word=w;}\n        for(int r=0;r<board.size();r++)for(int c=0;c<board[0].size();c++)dfs(board,r,c,root);\n        return res;\n    }\n    void dfs(vector<vector<char>>& b,int r,int c,Node* n) {\n        if(r<0||r>=(int)b.size()||c<0||c>=(int)b[0].size()||b[r][c]=='#'||!n->ch[b[r][c]-'a']) return;\n        char ch=b[r][c]; n=n->ch[ch-'a'];\n        if(!n->word.empty()){res.push_back(n->word);n->word=\"\";}\n        b[r][c]='#';\n        dfs(b,r+1,c,n);dfs(b,r-1,c,n);dfs(b,r,c+1,n);dfs(b,r,c-1,n);\n        b[r][c]=ch;\n    }\n};"),
      {time:'O(m*n*4^L)',space:'O(total chars)',simpleExplanation:"DFS from each cell, up to 4^L paths per word of length L."},
      "WORD SEARCH II = build Trie from words, DFS grid following Trie simultaneously. End node → found word!",
      [mcq("Why use a Trie instead of searching each word separately?",["Trie shares prefixes — words with common prefixes share DFS paths, avoiding redundant work","Tries are simpler","No advantage","Tries use less memory"],0,"Words like 'eat' and 'ear' share the 'ea' prefix. With a Trie, we only DFS through 'ea' once!")],
      ["Building a Trie lets you search for all words simultaneously.","DFS from each cell, but guided by the Trie — no Trie node means no word can start here.","Mark visited cells to avoid reuse. Restore after DFS."],
      ["Searching each word separately (O(words * m*n*4^L) vs O(m*n*4^L))","Not pruning dead branches in the Trie","Forgetting to restore visited cells"]
    ),
  ]);

  // ==================== HEAP / PRIORITY QUEUE (7) ====================
  console.log('\n⛰️ Heap / Priority Queue');
  await seedTopic('heap-priority-queue', [
    p('Kth Largest Element in a Stream','kth-largest-element-in-a-stream','EASY',1,
      "Keep track of the kth largest element as numbers stream in. Use a min-heap of size k! The top of the heap is always the kth largest. If a new number is bigger than the top, swap it in.",
      'Min-Heap of Size K','Maintain a min-heap with exactly k elements. The top is the kth largest. On add: if new > top, replace.',
      [{step:1,description:"k=3, stream: [4,5,8,2]",diagram:"Heap: [4,5,8] → top=4 = 3rd largest"},{step:2,description:"Add 3 (3<4, ignore). Add 5 → heap [4,5,5]→top=4. Add 10 → [5,5,10]→top=5",diagram:"kth largest updates as stream grows"}],
      sol("import heapq\nclass KthLargest:\n    def __init__(self, k, nums):\n        self.k = k\n        self.heap = nums\n        heapq.heapify(self.heap)\n        while len(self.heap) > k:\n            heapq.heappop(self.heap)\n    def add(self, val):\n        heapq.heappush(self.heap, val)\n        if len(self.heap) > self.k:\n            heapq.heappop(self.heap)\n        return self.heap[0]",
        "class KthLargest {\n    PriorityQueue<Integer> pq=new PriorityQueue<>();\n    int k;\n    public KthLargest(int k, int[] nums) {\n        this.k=k;\n        for (int n:nums) add(n);\n    }\n    public int add(int val) {\n        pq.add(val);\n        if (pq.size()>k) pq.poll();\n        return pq.peek();\n    }\n}",
        "class KthLargest {\n    priority_queue<int,vector<int>,greater<int>> pq;\n    int k;\npublic:\n    KthLargest(int k, vector<int>& nums): k(k) { for(int n:nums) add(n); }\n    int add(int val) {\n        pq.push(val);\n        if((int)pq.size()>k) pq.pop();\n        return pq.top();\n    }\n};"),
      {time:'O(log k) per add',space:'O(k)',simpleExplanation:"Heap operations on k elements = O(log k)."},
      "KTH LARGEST STREAM = MIN-HEAP of size k. Top is always the kth largest!",
      [mcq("Why a min-heap and not a max-heap?",["Min-heap's top is the smallest of the k largest elements = the kth largest","Max-heap is slower","No difference","Min-heap uses less memory"],0,"We keep the k largest elements. The smallest among them (min-heap top) is the kth largest overall.")],
      ["Keep only the k largest elements you've seen.","A min-heap of size k: the top = smallest of top k = kth largest.","On add: push to heap. If size > k, pop the smallest."],
      ["Using a max-heap (gives 1st largest, not kth)","Not limiting heap size to k","Forgetting to handle initial array"]
    ),
    p('Last Stone Weight','last-stone-weight','EASY',2,
      "Smash the two heaviest stones together. If equal, both destroyed. If not, the difference remains. Use a max-heap! Pop two heaviest, push difference if any. Last stone standing wins!",
      'Max-Heap Simulation','Use max-heap. Pop two largest, push |difference| if non-zero. Repeat until ≤1 stone remains.',
      [{step:1,description:"stones = [2,7,4,1,8,1]",diagram:"Pop 8,7 → push 1. Pop 4,2 → push 2. Pop 2,1 → push 1. Pop 1,1 → gone. Pop 1 → answer: 1"}],
      sol("import heapq\ndef lastStoneWeight(stones):\n    stones = [-s for s in stones]\n    heapq.heapify(stones)\n    while len(stones) > 1:\n        a = -heapq.heappop(stones)\n        b = -heapq.heappop(stones)\n        if a != b:\n            heapq.heappush(stones, -(a - b))\n    return -stones[0] if stones else 0",
        "public int lastStoneWeight(int[] stones) {\n    PriorityQueue<Integer> pq=new PriorityQueue<>(Collections.reverseOrder());\n    for (int s:stones) pq.add(s);\n    while (pq.size()>1) {\n        int a=pq.poll(), b=pq.poll();\n        if (a!=b) pq.add(a-b);\n    }\n    return pq.isEmpty()?0:pq.peek();\n}",
        "int lastStoneWeight(vector<int>& stones) {\n    priority_queue<int> pq(stones.begin(),stones.end());\n    while (pq.size()>1) {\n        int a=pq.top(); pq.pop();\n        int b=pq.top(); pq.pop();\n        if (a!=b) pq.push(a-b);\n    }\n    return pq.empty()?0:pq.top();\n}"),
      {time:'O(n log n)',space:'O(n)',simpleExplanation:"n stones, each operation O(log n) = O(n log n)."},
      "STONE SMASH = MAX-HEAP. Pop two heaviest, push difference. Repeat!",
      [mcq("Why max-heap?",["We need the two heaviest stones each round","Min-heap would also work","It's arbitrary","For efficiency"],0,"The problem requires smashing the two HEAVIEST. Max-heap gives O(1) access to the maximum.")],
      ["Always smash the two heaviest. What gives quick access to the max?","Max-heap! Pop two, push difference if non-zero.","Continue until ≤1 stone remains."],
      ["Python has no max-heap — negate values for min-heap","Not handling the empty heap case"]
    ),
    p('K Closest Points to Origin','k-closest-points-to-origin','MEDIUM',3,
      "Find k points closest to (0,0). Distance = x²+y² (no need for sqrt!). Use a max-heap of size k — if a new point is closer than the farthest in the heap, swap it in.",
      'Max-Heap of Size K','Use max-heap of size k by distance. For each point, if closer than heap top, replace. Heap contains k closest at the end.',
      [{step:1,description:"points=[[1,3],[-2,2]], k=1",diagram:"dist([1,3])=10, dist([-2,2])=8. Closest: [-2,2] ✅"}],
      sol("import heapq\ndef kClosest(points, k):\n    return heapq.nsmallest(k, points, key=lambda p: p[0]**2 + p[1]**2)",
        "public int[][] kClosest(int[][] points, int k) {\n    PriorityQueue<int[]> pq=new PriorityQueue<>((a,b)->(b[0]*b[0]+b[1]*b[1])-(a[0]*a[0]+a[1]*a[1]));\n    for (int[] p:points) { pq.add(p); if(pq.size()>k) pq.poll(); }\n    return pq.toArray(new int[0][]);\n}",
        "vector<vector<int>> kClosest(vector<vector<int>>& points, int k) {\n    auto cmp=[](vector<int>&a,vector<int>&b){return a[0]*a[0]+a[1]*a[1]<b[0]*b[0]+b[1]*b[1];};\n    priority_queue<vector<int>,vector<vector<int>>,decltype(cmp)> pq(cmp);\n    for(auto& p:points){pq.push(p);if((int)pq.size()>k)pq.pop();}\n    vector<vector<int>> res;\n    while(!pq.empty()){res.push_back(pq.top());pq.pop();}\n    return res;\n}"),
      {time:'O(n log k)',space:'O(k)',simpleExplanation:"n points, heap of size k = O(n log k)."},
      "K CLOSEST = max-heap of size k by distance. Top = farthest of the k closest. Replace if closer found.",
      [mcq("Why use x²+y² instead of sqrt(x²+y²)?",["Faster — sqrt is expensive and unnecessary for comparison","More accurate","Required by the problem","No difference"],0,"We only need to COMPARE distances. Since sqrt is monotonic, x²+y² preserves the ordering. Skip the sqrt!")],
      ["Distance to origin = x²+y². No need for sqrt!","Keep k closest using a max-heap of size k.","If new point is closer than heap top (farthest of k), replace."],
      ["Computing sqrt unnecessarily","Using min-heap (would need to keep all n points)"]
    ),
    p('Kth Largest Element in an Array','kth-largest-element-in-an-array','MEDIUM',4,
      "Find the kth largest without fully sorting. Min-heap of size k: process all elements, top = kth largest. Or use QuickSelect for average O(n)!",
      'Min-Heap of Size K (or QuickSelect)','Min-heap of size k. Process all elements. Top of heap = kth largest.',
      [{step:1,description:"nums=[3,2,1,5,6,4], k=2",diagram:"Heap keeps 2 largest: [5,6]. Top=5 = 2nd largest ✅"}],
      sol("import heapq\ndef findKthLargest(nums, k):\n    heap = []\n    for num in nums:\n        heapq.heappush(heap, num)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]",
        "public int findKthLargest(int[] nums, int k) {\n    PriorityQueue<Integer> pq=new PriorityQueue<>();\n    for (int n:nums) { pq.add(n); if(pq.size()>k) pq.poll(); }\n    return pq.peek();\n}",
        "int findKthLargest(vector<int>& nums, int k) {\n    priority_queue<int,vector<int>,greater<int>> pq;\n    for(int n:nums){pq.push(n);if((int)pq.size()>k)pq.pop();}\n    return pq.top();\n}"),
      {time:'O(n log k)',space:'O(k)',simpleExplanation:"Process n elements with heap of size k = O(n log k)."},
      "KTH LARGEST = min-heap of size k. After processing all, top = answer!",
      [mcq("Min-heap or max-heap for kth largest?",["Max-heap","Min-heap of size k — top is the smallest of the k largest = kth largest","Either works the same","Neither"],1,"Min-heap of size k: we keep the k largest values. The smallest among them (heap top) is the kth largest.")],
      ["Keep only the k largest elements seen so far.","Min-heap of size k does this automatically.","Process all elements, answer is heap top."],
      ["Using max-heap without size limit","Sorting the entire array (O(n log n) vs O(n log k))"]
    ),
    p('Task Scheduler','task-scheduler','MEDIUM',5,
      "Schedule tasks with cooldown n between same tasks. Most frequent task determines the minimum time. Greedy: schedule most frequent first, fill gaps with other tasks or idle.",
      'Greedy + Math','Time = (maxFreq-1) * (n+1) + countOfMaxFreq. Or total tasks if no idle needed.',
      [{step:1,description:"tasks=['A','A','A','B','B','B'], n=2",diagram:"A_B_A_B_A_B → slots = (3-1)*(2+1)+2 = 8"}],
      sol("def leastInterval(tasks, n):\n    freq = [0]*26\n    for t in tasks: freq[ord(t)-ord('A')] += 1\n    max_freq = max(freq)\n    max_count = freq.count(max_freq)\n    return max(len(tasks), (max_freq-1)*(n+1)+max_count)",
        "public int leastInterval(char[] tasks, int n) {\n    int[] freq=new int[26];\n    for (char t:tasks) freq[t-'A']++;\n    int maxF=Arrays.stream(freq).max().getAsInt();\n    int maxC=(int)Arrays.stream(freq).filter(f->f==maxF).count();\n    return Math.max(tasks.length,(maxF-1)*(n+1)+maxC);\n}",
        "int leastInterval(vector<char>& tasks, int n) {\n    int freq[26]={};\n    for(char t:tasks) freq[t-'A']++;\n    int maxF=*max_element(freq,freq+26);\n    int maxC=count(freq,freq+26,maxF);\n    return max((int)tasks.size(),(maxF-1)*(n+1)+maxC);\n}"),
      {time:'O(n)',space:'O(1)',simpleExplanation:"Count frequencies O(n), math formula O(1). 26-slot array = O(1)."},
      "TASK SCHEDULER = (maxFreq-1) * (cooldown+1) + countOfMaxFreq. Or total tasks if larger!",
      [mcq("Why does the most frequent task matter most?",["It creates the most gaps (idle slots) that need to be filled","It runs first","It's alphabetically first","It doesn't matter"],0,"The most frequent task creates (maxFreq-1) gaps of size n. Other tasks fill these gaps. Any remaining gaps = idle time.")],
      ["The most frequent task creates gaps that need filling.","Formula: (maxFreq-1)*(n+1)+countOfMaxFreq.","Take max of formula and total tasks (no idle if tasks fill all gaps)."],
      ["Not considering multiple tasks with max frequency","Simulating instead of using the formula (works but harder)"]
    ),
    p('Design Twitter','design-twitter','MEDIUM',6,
      "Design a simplified Twitter: postTweet, getNewsFeed (10 most recent from followed), follow, unfollow. Use a hash map for follows, a list with timestamps for tweets, and a merge of k sorted lists for the feed!",
      'HashMap + Merge K Sorted','Follow set per user. Tweets list with timestamp per user. getNewsFeed = merge recent tweets from all followed users (including self).',
      [{step:1,description:"user1 posts, follows user2, user2 posts",diagram:"getNewsFeed(1) → merged tweets from user1 and user2"}],
      sol("import heapq\nclass Twitter:\n    def __init__(self):\n        self.time = 0\n        self.tweets = {}  # userId -> [(time, tweetId)]\n        self.follows = {}  # userId -> set(followeeIds)\n    def postTweet(self, userId, tweetId):\n        self.tweets.setdefault(userId, []).append((self.time, tweetId))\n        self.time -= 1  # negative for max-heap\n    def getNewsFeed(self, userId):\n        self.follows.setdefault(userId, set()).add(userId)\n        heap = []\n        for fid in self.follows[userId]:\n            if fid in self.tweets and self.tweets[fid]:\n                idx = len(self.tweets[fid]) - 1\n                t, tid = self.tweets[fid][idx]\n                heapq.heappush(heap, (t, tid, fid, idx))\n        feed = []\n        while heap and len(feed) < 10:\n            t, tid, fid, idx = heapq.heappop(heap)\n            feed.append(tid)\n            if idx > 0:\n                nt, ntid = self.tweets[fid][idx-1]\n                heapq.heappush(heap, (nt, ntid, fid, idx-1))\n        return feed\n    def follow(self, followerId, followeeId):\n        self.follows.setdefault(followerId, set()).add(followeeId)\n    def unfollow(self, followerId, followeeId):\n        if followerId in self.follows: self.follows[followerId].discard(followeeId)",
        "// Java implementation uses similar HashMap + PriorityQueue approach\nclass Twitter {\n    int time=0;\n    Map<Integer,List<int[]>> tweets=new HashMap<>();\n    Map<Integer,Set<Integer>> follows=new HashMap<>();\n    public void postTweet(int userId,int tweetId){tweets.computeIfAbsent(userId,k->new ArrayList<>()).add(new int[]{time++,tweetId});}\n    public List<Integer> getNewsFeed(int userId){\n        follows.computeIfAbsent(userId,k->new HashSet<>()).add(userId);\n        PriorityQueue<int[]> pq=new PriorityQueue<>((a,b)->b[0]-a[0]);\n        for(int fid:follows.get(userId)){\n            var tw=tweets.get(fid);\n            if(tw!=null&&!tw.isEmpty()){int i=tw.size()-1;pq.add(new int[]{tw.get(i)[0],tw.get(i)[1],fid,i});}\n        }\n        List<Integer> feed=new ArrayList<>();\n        while(!pq.isEmpty()&&feed.size()<10){\n            int[] top=pq.poll();feed.add(top[1]);\n            if(top[3]>0){int i=top[3]-1;var tw=tweets.get(top[2]);pq.add(new int[]{tw.get(i)[0],tw.get(i)[1],top[2],i});}\n        }\n        return feed;\n    }\n    public void follow(int a,int b){follows.computeIfAbsent(a,k->new HashSet<>()).add(b);}\n    public void unfollow(int a,int b){if(follows.containsKey(a))follows.get(a).remove(b);}\n}",
        "// C++ uses similar unordered_map + priority_queue approach\nclass Twitter {\n    int time=0;\n    unordered_map<int,vector<pair<int,int>>> tweets;\n    unordered_map<int,unordered_set<int>> follows;\npublic:\n    void postTweet(int u,int t){tweets[u].push_back({time++,t});}\n    vector<int> getNewsFeed(int u){\n        follows[u].insert(u);\n        auto cmp=[](auto&a,auto&b){return get<0>(a)<get<0>(b);};\n        priority_queue<tuple<int,int,int,int>,vector<tuple<int,int,int,int>>,decltype(cmp)> pq(cmp);\n        for(int f:follows[u]){\n            auto&tw=tweets[f];\n            if(!tw.empty()){int i=tw.size()-1;pq.push({tw[i].first,tw[i].second,f,i});}\n        }\n        vector<int> feed;\n        while(!pq.empty()&&feed.size()<10){\n            auto[t,tid,fid,idx]=pq.top();pq.pop();feed.push_back(tid);\n            if(idx>0){int i=idx-1;pq.push({tweets[fid][i].first,tweets[fid][i].second,fid,i});}\n        }\n        return feed;\n    }\n    void follow(int a,int b){follows[a].insert(b);}\n    void unfollow(int a,int b){follows[a].erase(b);}\n};"),
      {time:'O(k log k) for feed',space:'O(users + tweets)',simpleExplanation:"getNewsFeed merges k users' tweets using a heap of size k."},
      "TWITTER = HashMap (follows) + List (tweets per user) + Heap (merge k sorted for feed)!",
      [mcq("Why use a heap for getNewsFeed?",["To sort all tweets","To efficiently merge the most recent tweets from k followed users","To count likes","For random access"],1,"Each followed user has a sorted tweet list. Merging k sorted lists efficiently = heap of size k!")],
      ["postTweet: append (timestamp, tweetId) to user's list.","getNewsFeed: merge k sorted lists using a min-heap.","follow/unfollow: maintain a set of followees per user."],
      ["Not including the user's own tweets in their feed","Forgetting to use timestamps for ordering"]
    ),
    p('Find Median from Data Stream','find-median-from-data-stream','HARD',7,
      "Find the median as numbers stream in. Use TWO heaps! A max-heap for the smaller half and a min-heap for the larger half. Median = top of max-heap (or average of both tops if even count).",
      'Two Heaps (Max + Min)','Max-heap stores smaller half, min-heap stores larger half. Balance sizes (differ by at most 1). Median is max-heap top or average of both tops.',
      [{step:1,description:"Stream: 1, 2, 3",diagram:"maxH=[1], minH=[2,3]. Rebalance: maxH=[1,2], minH=[3]. Median=(2+3)/2=2.5? No: maxH=[2,1], minH=[3]. Median=2"}],
      sol("import heapq\nclass MedianFinder:\n    def __init__(self):\n        self.lo = []  # max-heap (negate)\n        self.hi = []  # min-heap\n    def addNum(self, num):\n        heapq.heappush(self.lo, -num)\n        heapq.heappush(self.hi, -heapq.heappop(self.lo))\n        if len(self.hi) > len(self.lo):\n            heapq.heappush(self.lo, -heapq.heappop(self.hi))\n    def findMedian(self):\n        if len(self.lo) > len(self.hi):\n            return -self.lo[0]\n        return (-self.lo[0] + self.hi[0]) / 2",
        "class MedianFinder {\n    PriorityQueue<Integer> lo=new PriorityQueue<>(Collections.reverseOrder());\n    PriorityQueue<Integer> hi=new PriorityQueue<>();\n    public void addNum(int num) {\n        lo.add(num); hi.add(lo.poll());\n        if (hi.size()>lo.size()) lo.add(hi.poll());\n    }\n    public double findMedian() {\n        return lo.size()>hi.size() ? lo.peek() : (lo.peek()+hi.peek())/2.0;\n    }\n}",
        "class MedianFinder {\n    priority_queue<int> lo;\n    priority_queue<int,vector<int>,greater<int>> hi;\npublic:\n    void addNum(int num) {\n        lo.push(num); hi.push(lo.top()); lo.pop();\n        if(hi.size()>lo.size()){lo.push(hi.top());hi.pop();}\n    }\n    double findMedian() {\n        return lo.size()>hi.size() ? lo.top() : (lo.top()+hi.top())/2.0;\n    }\n};"),
      {time:'O(log n) add, O(1) median',space:'O(n)',simpleExplanation:"Heap push/pop = O(log n). Median = peek at tops = O(1)."},
      "STREAMING MEDIAN = TWO HEAPS. Max-heap (small half) + Min-heap (large half). Balance sizes. Median from tops!",
      [mcq("Why two heaps?",["To split the data into smaller and larger halves, giving O(1) median access","Two is better than one","To sort the data","For memory efficiency"],0,"Max-heap top = largest of small half. Min-heap top = smallest of large half. These are the two middle elements!")],
      ["Split numbers into two halves: smaller (max-heap) and larger (min-heap).","Keep them balanced: sizes differ by at most 1.","Median = max-heap top (odd count) or average of both tops (even)."],
      ["Not rebalancing heaps after insertion","Using a single sorted array (O(n) insert vs O(log n))"]
    ),
  ]);

  const total = await prisma.problem.count();
  console.log(`\n🎉 Done! Total problems: ${total}/150`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
